### ISSUE TITLE
Crash when inviting some contact into a MUC

### ISSUE THREAD

**Issue by marc0s** [siacs/Conversations#1188]
Hi,

just tried and retried a few times and the same behavior is repeated: when inviting a contact to a conference, Conversations crashes.

```
D/conversations(26339): app switched into foreground
D/conversations(26339): load more messages for familia prior to 2015-05-11T20:30:25Z
I/ActivityManager(  833): Displayed eu.siacs.conversations/.ui.ConversationActivity: +296ms
I/Timeline(26339): Timeline: Activity_idle id: android.os.BinderProxy@3fc2468e time:12360815
I/Timeline(  833): Timeline: Activity_windows_visible id: ActivityRecord{2bcc6b06 u0 eu.siacs.conversations/.ui.ConversationActivity t309} time:12361020
I/art     ( 2760): Explicit concurrent mark sweep GC freed 5277(421KB) AllocSpace objects, 0(0B) LOS objects, 24% free, 17MB/23MB, paused 717us total 42.047ms
I/art     ( 2760): Explicit concurrent mark sweep GC freed 11295(848KB) AllocSpace objects, 9(481KB) LOS objects, 24% free, 16MB/21MB, paused 701us total 37.363ms
I/art     ( 2760): Explicit concurrent mark sweep GC freed 25(5KB) AllocSpace objects, 0(0B) LOS objects, 25% free, 16MB/21MB, paused 707us total 32.536ms
V/WindowManager(  833): Adding window Window{39875cd6 u0 PopupWindow:8dae560} at 2 of 8 (after Window{e8bea75 u0 eu.siacs.conversations/eu.siacs.conversations.ui.ConversationActivity})
E/AudioTrack(  833): AudioTrack::set : Exit
I/Timeline(26339): Timeline: Activity_launch_request id:eu.siacs.conversations time:12368806
I/ActivityManager(  833): START u0 {cmp=eu.siacs.conversations/.ui.ChooseContactActivity (has extras)} from uid 10065 on display 0
V/WindowManager(  833): addAppToken: AppWindowToken{299de5f3 token=Token{30747062 ActivityRecord{1063f32d u0 eu.siacs.conversations/.ui.ChooseContactActivity t309}}} to stack=1 task=309 at 1
V/WindowManager(  833): Adding window Window{fc9b9dc u0 eu.siacs.conversations/eu.siacs.conversations.ui.ChooseContactActivity} at 3 of 9 (after Window{39875cd6 u0 PopupWindow:8dae560 EXITING})
I/ActivityManager(  833): Displayed eu.siacs.conversations/.ui.ChooseContactActivity: +233ms
I/Timeline(26339): Timeline: Activity_idle id: android.os.BinderProxy@1abe303e time:12369091
I/Timeline(  833): Timeline: Activity_windows_visible id: ActivityRecord{1063f32d u0 eu.siacs.conversations/.ui.ChooseContactActivity t309} time:12369443
D/conversations(26339): app switched into background
E/AudioTrack(  833): AudioTrack::set : Exit
V/WindowManager(  833): Adding window Window{28f697e0 u0 Starting eu.siacs.conversations} at 1 of 8 (before Window{fc9b9dc u0 eu.siacs.conversations/eu.siacs.conversations.ui.ChooseContactActivity})
D/AndroidRuntime(26339): Shutting down VM
E/AndroidRuntime(26339): FATAL EXCEPTION: main
E/AndroidRuntime(26339): Process: eu.siacs.conversations, PID: 26339
E/AndroidRuntime(26339): java.lang.RuntimeException: Unable to resume activity {eu.siacs.conversations/eu.siacs.conversations.ui.ConversationActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=258, result=-1, data=Intent { (has extras) }} to activity {eu.siacs.conversations/eu.siacs.conversations.ui.ConversationActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'eu.siacs.conversations.entities.Conversation eu.siacs.conversations.services.XmppConnectionService.findConversationByUuid(java.lang.String)' on a null object reference
E/AndroidRuntime(26339): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3017)
E/AndroidRuntime(26339): 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3048)
E/AndroidRuntime(26339): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2423)
E/AndroidRuntime(26339): 	at android.app.ActivityThread.access$900(ActivityThread.java:154)
E/AndroidRuntime(26339): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
E/AndroidRuntime(26339): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(26339): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(26339): 	at android.app.ActivityThread.main(ActivityThread.java:5293)
E/AndroidRuntime(26339): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(26339): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(26339): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
E/AndroidRuntime(26339): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
E/AndroidRuntime(26339): Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=258, result=-1, data=Intent { (has extras) }} to activity {eu.siacs.conversations/eu.siacs.conversations.ui.ConversationActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'eu.siacs.conversations.entities.Conversation eu.siacs.conversations.services.XmppConnectionService.findConversationByUuid(java.lang.String)' on a null object reference
E/AndroidRuntime(26339): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3605)
E/AndroidRuntime(26339): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3003)
E/AndroidRuntime(26339): 	... 11 more
E/AndroidRuntime(26339): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'eu.siacs.conversations.entities.Conversation eu.siacs.conversations.services.XmppConnectionService.findConversationByUuid(java.lang.String)' on a null object reference
E/AndroidRuntime(26339): 	at eu.siacs.conversations.ui.XmppActivity.onActivityResult(XmppActivity.java:672)
E/AndroidRuntime(26339): 	at eu.siacs.conversations.ui.ConversationActivity.onActivityResult(ConversationActivity.java:994)
E/AndroidRuntime(26339): 	at android.app.Activity.dispatchActivityResult(Activity.java:6192)
E/AndroidRuntime(26339): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3601)
E/AndroidRuntime(26339): 	... 12 more
W/ActivityManager(  833):   Force finishing activity 1 eu.siacs.conversations/.ui.ConversationActivity
I/OpenGLRenderer(  833): Initialized EGL, version 1.4
W/ActivityManager(  833): Activity pause timeout for ActivityRecord{2bcc6b06 u0 eu.siacs.conversations/.ui.ConversationActivity t309 f}
```

Using Conversations 1.3.1 from fdroid and CM12.1.

**Comment by iNPUTmice** [comment]
Out of curiosity: Do you have the **Don't keep activities** setting enabled in your developer options or are you using some sort of 'memory optimizer'? Or do you have a phone with very few resources? Because this is the only way I could reproduce this.

Anyway fix will be pushed to [Beta Channel](http://conversations.im/#beta) within the next couple of hours.

**Comment by marc0s** [comment]
Actually I had the Don't keep activities setting turned on. Disabling it solved the crash.

Thanks for the quick answer and fix!

On 12 May 2015 04:37:12 CEST, Daniel Gultsch <notifications@github.com> wrote:
>Out of curiosity: Do you have the **Don't keep activities** setting
>enabled in your developer options or are you using some sort of 'memory
>optimizer'? Or do you have a phone with very few resources? Because
>this is the only way I could reproduce this.
>
>Anyway fix will be pushed to [Beta
>Channel](http://conversations.im/#beta) within the next couple of
>hours.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/siacs/Conversations/issues/1188#issuecomment-101107638

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
