### ISSUE TITLE
io exception in http file size checker

### ISSUE THREAD

**Issue by kriztan** [siacs/Conversations#1336]
I've retrieved an video file via link and the video can not be downloaded with conversations. 
I'm getting the following error in the ADB logs:

`08-18 20:26:09.140  9932  9932 I menu_item_selected: [1,Lade Video herunter]: eu.siacs.conversations
08-18 20:26:09.145  9932  5232 D conversations: retrieve file size. interactive:true: eu.siacs.conversations
08-18 20:26:09.165  2318  2318 I notification_cancel: [eu.siacs.conversations,9026,NULL,0,0,64]: system_server
08-18 20:26:09.365  1901  1901 I sf_frame_dur: [AtchDlg:eu.siacs.conversations/eu.siacs.conversations.ui.ConversationActivity,0,2,0,0,0,2,0]: /system/bin/surfaceflinger
08-18 20:26:11.560  9932  5232 D conversations: io exception in http file size checker: null: eu.siacs.conversations
08-18 20:26:11.560  9932  5232 W System.err: java.io.IOException: eu.siacs.conversations
08-18 20:26:11.560  9932  5232 W System.err: 	at eu.siacs.conversations.http.HttpDownloadConnection$FileSizeChecker.retrieveFileSize(HttpDownloadConnection.java:191): eu.siacs.conversations
08-18 20:26:11.560  9932  5232 W System.err: 	at eu.siacs.conversations.http.HttpDownloadConnection$FileSizeChecker.run(HttpDownloadConnection.java:153): eu.siacs.conversations
08-18 20:26:11.560  9932  5232 W System.err: 	at java.lang.Thread.run(Thread.java:841): eu.siacs.conversations
08-18 20:26:11.580  2318  2318 I notification_cancel: [eu.siacs.conversations,9026,NULL,0,0,64]: system_server`

We both are using self compiled Conversations 1.6.0

**Comment by kriztan** [comment]
Oh, I've seen that my server didn't send the content-length because of activated compression. I've disabled this and now it's working.
