### ISSUE TITLE
Conversations crashes upon opening when installed as system app

### ISSUE THREAD

**Issue by f3rnando** [siacs/Conversations#1384]
Version: 1.6.7
Last Update: 31 de agosto, 2:26 p.m.
java.lang.VerifyError: org/whispersystems/curve25519/java/fe_mul
    at org.whispersystems.curve25519.java.ge_madd.ge_madd(ge_madd.java:65)
    at org.whispersystems.curve25519.java.ge_scalarmult_base.ge_scalarmult_base(ge_scalarmult_base.java:96)
    at org.whispersystems.curve25519.java.curve_sigs.curve25519_keygen(curve_sigs.java:30)
    at org.whispersystems.curve25519.BaseJavaCurve25519Provider.generatePublicKey(BaseJavaCurve25519Provider.java:50)
    at org.whispersystems.curve25519.JavaCurve25519Provider.generatePublicKey(JavaCurve25519Provider.java:8)
    at org.whispersystems.curve25519.OpportunisticCurve25519Provider.generatePublicKey(OpportunisticCurve25519Provider.java:27)
    at org.whispersystems.curve25519.Curve25519.generateKeyPair(Curve25519.java:70)
    at org.whispersystems.libaxolotl.ecc.Curve.generateKeyPair(Curve.java:35)
    at eu.siacs.conversations.crypto.axolotl.SQLiteAxolotlStore.generateIdentityKeyPair(SQLiteAxolotlStore.java:62)
    at eu.siacs.conversations.crypto.axolotl.SQLiteAxolotlStore.loadIdentityKeyPair(SQLiteAxolotlStore.java:99)
    at eu.siacs.conversations.crypto.axolotl.SQLiteAxolotlStore.getIdentityKeyPair(SQLiteAxolotlStore.java:157)
    at eu.siacs.conversations.crypto.axolotl.AxolotlService$4.onIqPacketReceived(AxolotlService.java:390)
    at eu.siacs.conversations.xmpp.XmppConnection.processIq(XmppConnection.java:500)
    at eu.siacs.conversations.xmpp.XmppConnection.processStream(XmppConnection.java:382)
    at eu.siacs.conversations.xmpp.XmppConnection.processStream(XmppConnection.java:294)
    at eu.siacs.conversations.xmpp.XmppConnection.switchOverToTls(XmppConnection.java:564)
    at eu.siacs.conversations.xmpp.XmppConnection.processStream(XmppConnection.java:280)
    at eu.siacs.conversations.xmpp.XmppConnection.connect(XmppConnection.java:220)
    at eu.siacs.conversations.xmpp.XmppConnection.run(XmppConnection.java:267)
    at java.lang.Thread.run(Thread.java:856)

**Comment by iNPUTmice** [comment]
If this exception is only getting thrown when installed as a system app you might want to report that upstream to either the libaxolotl-java or the curve25519 library because simply catching it in Conversations would probably break stuff.

**Comment by strb** [comment]
See WhisperSystems/curve25519-java#4

**Comment by Aasaqt** [comment]
Getting same error. Please help to resolve it.

**Comment by mimi89999** [comment]
@Aasaqt Also running Conversations as a system app or getting the same error running conversations normally!

**Comment by Aasaqt** [comment]
Getting the error when running conversation as a system app

**Comment by mimi89999** [comment]
Out of curiosity: why are you running Conversations as a system app? Is there an Android ROM, that has it?

**Comment by iNPUTmice** [comment]
You need to update to the latest version of libsignal. And if you do please
create a PR.

**Comment by Aasaqt** [comment]
Actually the problem comes when i updated the latest version of conversation from 15 to 16.

**Comment by Aasaqt** [comment]
@mimi89999 Actually i am using conversation as a module for chat purpose in the application which i am building for different purposes. So there I have to forcefully change the minSdkVerion to 16 from 15 which causes the problem.

**Comment by iNPUTmice** [comment]
@Aasaqt like I said. You need to update the libsignalprotocol version.

**Comment by mimi89999** [comment]
> Getting the error when running conversation as a system app

> Actually i am using conversation as a module for chat purpose in the application which i am building for different purposes.

😶

**Comment by Aasaqt** [comment]
@iNPUTmice How can i do so ? I am not getting the way to update this.

**Comment by mimi89999** [comment]
@Aasaqt In the `gradle.build` file.

**Comment by iNPUTmice** [comment]
I'm also available for hire if you need this for your business. Contact
information are on my website.
