### ISSUE TITLE
Nullpointer when sending PGP in MUC

### ISSUE THREAD

**Issue by halemmerich** [siacs/Conversations#1544]
Sending a PGP message in MUC creates a force close the moment then send-button is touched. Not encrypted sending works as intended and receiving of both plaintext and PGP also.

D/conversations(31218): app switched into foreground
E/AndroidRuntime(31218): Process: eu.siacs.conversations, PID: 31218
E/AndroidRuntime(31218): java.lang.NullPointerException: Attempt to invoke virtual method 'eu.siacs.conversations.entities.Account eu.siacs.conversations.entities.Contact.getAccount()' on a null object reference
E/AndroidRuntime(31218): 	at eu.siacs.conversations.crypto.PgpEngine$3.onReturn(PgpEngine.java:163)
W/ActivityManager(  613):   Force finishing activity eu.siacs.conversations/.ui.ConversationActivity

**Comment by Polynomdivison** [comment]
Same problem here.

    Version: 1.7.2
    Last Update: 6. November 00:07
    java.lang.NullPointerException: Attempt to invoke virtual method 'eu.siacs.conversations.entities.Account eu. siacs.conversations.entities.Contact.getAccount()' on a null object reference
    at eu.siacs.conversations.crypto.PgpEngine$3.onReturn(PgpEngine.java:163)
    at org.openintents.openpgp.util.OpenPgpApi$OpenPgpAsyncTask.onPostExecute(OpenPgpApi.java:232)
    at org.openintents.openpgp.util.OpenPgpApi$OpenPgpAsyncTask.onPostExecute(OpenPgpApi.java:213)
    at android.os.AsyncTask.finish(AsyncTask.java:636)
    at android.os.AsyncTask.access$500(AsyncTask.java:177)
    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
    at android.os.Handler.dispatchMessage(Handler.java:111)
    at android.os.Looper.loop(Looper.java:194)
    at android.app.ActivityThread.main(ActivityThread.java:5637)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
