### ISSUE TITLE
Conversations crashes instantly after PGP-Key was assigned, NullPointerException at eu.siacs.conversations.crypto.PgpEngine$1.onReturn(PgpEngine.java:53)

### ISSUE THREAD

**Issue by lupusmeatus** [siacs/Conversations#1568]
And it continues crashing when device and application are restarted. Observed with conversations 1.7.2 on Android 6.

...
11-14 06:38:38.164   853  1279 W PackageManager: Unknown permission com.majeur.launcher.permission.UPDATE_BADGE in package eu.siacs.conversations
11-14 06:38:40.937   853   868 I ActivityManager: Start proc 1772:eu.siacs.conversations/u0a101 for broadcast eu.siacs.conversations/.services.EventReceiver
11-14 06:38:43.954  1772  1772 E AndroidRuntime: FATAL EXCEPTION: main
11-14 06:38:43.954  1772  1772 E AndroidRuntime: Process: eu.siacs.conversations, PID: 1772
11-14 06:38:43.954  1772  1772 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'eu.siacs.conversations.entities.Account eu.siacs.conversations.entities.Contact.getAccount()' on a null object reference
11-14 06:38:43.954  1772  1772 E AndroidRuntime: 	at eu.siacs.conversations.crypto.PgpEngine$1.onReturn(PgpEngine.java:53)
11-14 06:38:43.954  1772  1772 E AndroidRuntime: 	at org.openintents.openpgp.util.OpenPgpApi$OpenPgpAsyncTask.onPostExecute(OpenPgpApi.java:232)
11-14 06:38:43.954  1772  1772 E AndroidRuntime: 	at org.openintents.openpgp.util.OpenPgpApi$OpenPgpAsyncTask.onPostExecute(OpenPgpApi.java:213)
11-14 06:38:43.954  1772  1772 E AndroidRuntime: 	at android.os.AsyncTask.finish(AsyncTask.java:651)
11-14 06:38:43.954  1772  1772 E AndroidRuntime: 	at android.os.AsyncTask.-wrap1(AsyncTask.java)
11-14 06:38:43.954  1772  1772 E AndroidRuntime: 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
11-14 06:38:43.954  1772  1772 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-14 06:38:43.954  1772  1772 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
11-14 06:38:43.954  1772  1772 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
11-14 06:38:43.954  1772  1772 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-14 06:38:43.954  1772  1772 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
11-14 06:38:43.954  1772  1772 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
11-14 06:38:44.007   853  1539 I ActivityManager: Process eu.siacs.conversations (pid 1772) has died
11-14 06:38:44.008   853  1539 W ActivityManager: Scheduling restart of crashed service eu.siacs.conversations/.services.XmppConnectionService in 1000ms
...

I attached a more complete log, created by replacing the account and server-names and doing a  grep "4734\|conversations\|1772". The server used was not example.net but jabber.at.

[conversation2a.txt](https://github.com/siacs/Conversations/files/34567/conversation2a.txt)

**Comment by lupusmeatus** [comment]
Seems to be the decrypt-counterpart of https://github.com/siacs/Conversations/issues/1544
