### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by K0genta** [siacs/Conversations#1692]
after a successful login conversation crashed with an ArrayIndexOutOfBoundsException

master / 1bb38e2

> 02-10 23:29:52.905    6216-6242/? E/AndroidRuntime﹕ FATAL EXCEPTION: Thread-541
    Process: eu.siacs.conversations, PID: 6216
    java.lang.ArrayIndexOutOfBoundsException: src.length=27 srcPos=1 dst.length=32 dstPos=0 length=32
            at java.lang.System.arraycopy(Native Method)
            at org.whispersystems.libaxolotl.ecc.Curve.decodePoint(Curve.java:49)
            at eu.siacs.conversations.parser.IqParser.preKeyPublics(IqParser.java:201)
            at eu.siacs.conversations.parser.IqParser.preKeys(IqParser.java:258)
            at eu.siacs.conversations.crypto.axolotl.AxolotlService$8.onIqPacketReceived(AxolotlService.java:704)
            at eu.siacs.conversations.xmpp.XmppConnection.processIq(XmppConnection.java:671)
            at eu.siacs.conversations.xmpp.XmppConnection.processStream(XmppConnection.java:558)
            at eu.siacs.conversations.xmpp.XmppConnection.processStream(XmppConnection.java:467)
            at eu.siacs.conversations.xmpp.XmppConnection.switchOverToTls(XmppConnection.java:723)
            at eu.siacs.conversations.xmpp.XmppConnection.processStream(XmppConnection.java:451)
            at eu.siacs.conversations.xmpp.XmppConnection.connect(XmppConnection.java:339)
            at eu.siacs.conversations.xmpp.XmppConnection.run(XmppConnection.java:440)
            at java.lang.Thread.run(Thread.java:818)

HTC-One m7
Cyanogenmod 12.1
Android 5.1.1

**Comment by iNPUTmice** [comment]
related: https://github.com/WhisperSystems/libaxolotl-java/issues/5
