### ISSUE TITLE
Crash after update to 1.12.0

### ISSUE THREAD

**Issue by kriztan** [siacs/Conversations#1825]
On my phone Conversations crashes after updating to 1.12.0 with the following error:

`05-03 21:14:38.251 4880-4928/eu.siacs.conversations E/AndroidRuntime: FATAL EXCEPTION: pool-2-thread-1
                                                                      Process: eu.siacs.conversations, PID: 4880
                                                                      com.google.protobuf.UninitializedMessageException: Message missing required fields: 
                                                                          at com.google.protobuf.AbstractMessage$Builder.newUninitializedMessageException(AbstractMessage.java:770)
                                                                          at org.whispersystems.libaxolotl.state.StorageProtos$SessionStructure$Builder.build(StorageProtos.java:4537)
                                                                          at org.whispersystems.libaxolotl.state.SessionState.<init>(SessionState.java:55)
                                                                          at org.whispersystems.libaxolotl.state.SessionRecord.<init>(SessionRecord.java:20)
                                                                          at eu.siacs.conversations.persistance.DatabaseBackend.loadSession(DatabaseBackend.java:736)
                                                                          at eu.siacs.conversations.crypto.axolotl.SQLiteAxolotlStore.loadSession(SQLiteAxolotlStore.java:253)
                                                                          at eu.siacs.conversations.crypto.axolotl.AxolotlService$SessionMap.putDevicesForJid(AxolotlService.java:165)
                                                                          at eu.siacs.conversations.crypto.axolotl.AxolotlService$SessionMap.fillMap(AxolotlService.java:186)
                                                                          at eu.siacs.conversations.crypto.axolotl.AxolotlService$SessionMap.<init>(AxolotlService.java:158)
                                                                          at eu.siacs.conversations.crypto.axolotl.AxolotlService.<init>(AxolotlService.java:233)
                                                                          at eu.siacs.conversations.entities.Account.initAccountServices(Account.java:387)
                                                                          at eu.siacs.conversations.services.XmppConnectionService$18.run(XmppConnectionService.java:1180)
                                                                          at eu.siacs.conversations.utils.SerialSingleThreadExecutor$1.run(SerialSingleThreadExecutor.java:18)
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                          at java.lang.Thread.run(Thread.java:818)`

**Comment by kriztan** [comment]
This seems to be solved. I've deleted Conversations data and added my account again and now it's working.

**Comment by jugrajsingh** [comment]
Getting same problem again

**Comment by licaon-kter** [comment]
New log?
