### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by chyk1991** [siacs/Conversations#1844]
Process: eu.siacs.conversations, PID: 30641
    java.lang.NullPointerException: Attempt to invoke virtual method 'void eu.siacs.conversations.crypto.PgpEngine.chooseKey(eu.siacs.conversations.entities.Account, eu.siacs.conversations.ui.UiCallback)' on a null object reference
    at eu.siacs.conversations.ui.XmppActivity.choosePgpSignId(XmppActivity.java:563)
    at eu.siacs.conversations.ui.XmppActivity.announcePgp(XmppActivity.java:499)
    at eu.siacs.conversations.ui.SetPresenceActivity.executeChangePresence(SetPresenceActivity.java:119)
    at eu.siacs.conversations.ui.SetPresenceActivity.access$000(SetPresenceActivity.java:30)
    at eu.siacs.conversations.ui.SetPresenceActivity$2.onClick(SetPresenceActivity.java:68)
    at android.view.View.performClick(View.java)
    at android.view.View$PerformClick.run(View.java)
    at android.os.Handler.handleCallback(Handler.java)
    at android.os.Handler.dispatchMessage(Handler.java)
    at android.os.Looper.loop(Looper.java)
    at android.app.ActivityThread.main(ActivityThread.java)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:165)

**Comment by iNPUTmice** [comment]
was fixed in 09e20f6e01f53ff1d4c038a5ff0cbd3d7868130a
