### ISSUE TITLE
Crash while activating account in the morning

### ISSUE THREAD

**Issue by schwindp** [siacs/Conversations#1859]
#### General information

* **Device: OnePlus X**
* **Android Version: Android 5.1.1 Stock**
* **Server name: self hosted**
* **Server software: prosody 0.10**
* **Installed server modules:Stream Management, CSI, MAM, carbons, cloud_notify, presence_cache, http_upload**
* **Conversations source: PlayStore** 

#### Steps to reproduce

1. Switch account to active

#### Expected result

Fully functional Conversations App.

#### What happened

Conversations gracefully died after receiving its MAM messages (including a bunch of OTR).

Starting up again after this happened worked fine, though.

#### Debug output

Version: 1.12.3
Last Update: 13. Mai 15:06
java.lang.NullPointerException: Attempt to read from field 'int eu.siacs.conversations.entities.Message.status' on a null object reference
at eu.siacs.conversations.entities.Message.getMergedStatus(Message.java:510)
at eu.siacs.conversations.ui.adapter.MessageAdapter.displayStatus(MessageAdapter.java:157)
at eu.siacs.conversations.ui.adapter.MessageAdapter.getView(MessageAdapter.java:672)
at android.widget.AbsListView.obtainView(AbsListView.java:2347)
at android.widget.ListView.makeAndAddView(ListView.java:1864)
at android.widget.ListView.fillUp(ListView.java:732)
at android.widget.ListView.layoutChildren(ListView.java:1654)
at android.widget.AbsListView.onLayout(AbsListView.java:2151)
at android.view.View.layout(View.java:15715)
at android.view.ViewGroup.layout(ViewGroup.java:5046)
at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1077)
at android.view.View.layout(View.java:15715)
at android.view.ViewGroup.layout(ViewGroup.java:5046)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
at android.view.View.layout(View.java:15715)
at android.view.ViewGroup.layout(ViewGroup.java:5046)
at android.support.v4.widget.SlidingPaneLayout.onLayout(SlidingPaneLayout.java:718)
at android.view.View.layout(View.java:15715)
at android.view.ViewGroup.layout(ViewGroup.java:5046)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
at android.view.View.layout(View.java:15715)
at android.view.ViewGroup.layout(ViewGroup.java:5046)
at com.android.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:494)
at android.view.View.layout(View.java:15715)
at android.view.ViewGroup.layout(ViewGroup.java:5046)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
at android.view.View.layout(View.java:15715)
at android.view.ViewGroup.layout(ViewGroup.java:5046)
at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2097)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1854)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1069)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5915)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
at android.view.Choreographer.doCallbacks(Choreographer.java:580)
at android.view.Choreographer.doFrame(Choreographer.java:550)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:139)
at android.app.ActivityThread.main(ActivityThread.java:5298)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:950)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745)

**Comment by iNPUTmice** [comment]
fixed in 627bf18f8cfa72aee3f410f22245403ff6a98ed0
