### ISSUE TITLE
Crash when selecting text in message 

### ISSUE THREAD

**Issue by thundergreen** [siacs/Conversations#1860]
#### General information

* **Device:** Cabot X11
* **Android Version:** 4.2.2
* **Server name:** emevth.no-ip.biz
* **Server software:** ejabberd 16.04
* **Installed server modules:** Stream Managment, CSI, MAM
* **Conversations source:** PlayStore, PlayStore Version: 1.12.3
Last Update: 13. Mai 6:11 nachm.
java.lang.IndexOutOfBoundsException: setSpan (-1 ... -1) starts before 0
	at android.text.SpannableStringInternal.checkRange(SpannableStringInternal.java:355)
	at android.text.SpannableStringInternal.setSpan(SpannableStringInternal.java:77)
	at android.text.SpannableString.setSpan(SpannableString.java:46)
	at android.text.Selection.setSelection(Selection.java:76)
	at android.widget.Editor$SelectionEndHandleView.updateSelection(Editor.java:3543)
	at android.widget.Editor$HandleView.positionAtCursorOffset(Editor.java:3223)
	at android.widget.Editor$SelectionEndHandleView.updatePosition(Editor.java:3563)
	at android.widget.Editor$HandleView.onTouchEvent(Editor.java:3316)
	at android.view.View.dispatchTouchEvent(View.java:7782)
	at android.view.View.dispatchPointerEvent(View.java:7973)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4392)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4263)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3809)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3859)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3828)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3935)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3836)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3992)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3809)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3859)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3828)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3836)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3809)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6124)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6104)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6058)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6254)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6216)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6276)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:788)
	at android.view.Choreographer.doCallbacks(Choreographer.java:591)
	at android.view.Choreographer.doFrame(Choreographer.java:558)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:774)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:5292)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
	at dalvik.system.NativeStart.main(Native Method) Steps to reproduce

1. …
2. …

#### Expected result

What is the expected output? What do you see instead?

#### Debug output

Please post the output of adb logcat. The log should begin with the start of Conversations and include all the
steps it takes to reproduce the problem.

````
adb logcat -s conversations
````

**Comment by iNPUTmice** [comment]
Does this happen all the time?

**Comment by thundergreen** [comment]
all the time without exception unfortunately. i think i already snt several
bug reports in the app

2016-05-18 9:38 GMT+02:00 Daniel Gultsch <notifications@github.com>:

**Comment by iNPUTmice** [comment]
Looks like a ROM problem then. Nothing we can do about that.
