### ISSUE TITLE
Conversations crashes in emulator

### ISSUE THREAD

**Issue by knoy** [siacs/Conversations#1964]
#### General information
- **Version:** latest
- **Device:** Marshmallow Emulator
- **Conversations source:** latest
#### Steps to reproduce
1. Deploy to emulator
2. Open app
#### Debug output

```
07-21 01:15:49.974 2394-2394/eu.siacs.conversations E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: eu.siacs.conversations, PID: 2394
                                                                      java.lang.RuntimeException: Unable to create service eu.siacs.conversations.services.XmppConnectionService: android.database.sqlite.SQLiteException: no such table: identities (code 1): , while compiling: ALTER TABLE identities ADD COLUMN certificate
                                                                          at android.app.ActivityThread.handleCreateService(ActivityThread.java:2887)
                                                                          at android.app.ActivityThread.-wrap4(ActivityThread.java)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1427)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:148)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                       Caused by: android.database.sqlite.SQLiteException: no such table: identities (code 1): , while compiling: ALTER TABLE identities ADD COLUMN certificate
                                                                          at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                                          at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:887)
                                                                          at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:498)
                                                                          at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                                                                          at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
                                                                          at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
                                                                          at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1674)
                                                                          at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1605)
                                                                          at eu.siacs.conversations.persistance.DatabaseBackend.onUpgrade(DatabaseBackend.java:339)
                                                                          at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:256)
                                                                          at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:187)
                                                                          at eu.siacs.conversations.persistance.DatabaseBackend.getAccounts(DatabaseBackend.java:595)
                                                                          at eu.siacs.conversations.services.XmppConnectionService.onCreate(XmppConnectionService.java:765)
                                                                          at android.app.ActivityThread.handleCreateService(ActivityThread.java:2877)
                                                                          at android.app.ActivityThread.-wrap4(ActivityThread.java) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1427) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:148) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

**Comment by iNPUTmice** [comment]
From what version did you upgrade and was that version somehow modified?

**Comment by DoM1niC** [comment]
I use Android x86 6.0 RC1 and all works fine....

**Comment by raytry** [comment]
Version 1.14.5 crashes at start on Samsung Galaxy S4 GT-I9506 with cm-13.0-20161010-NIGHTLY-ks01lte.

**Comment by raytry** [comment]
When I turned the SELinux status to "permissive" with the `setenforce 0` command at root terminal, it starts normal.
