### ISSUE TITLE
TLS certificate verification error on Android 7.1.1

### ISSUE THREAD

**Issue by zwobbl** [siacs/Conversations#2316]
After upgrading my Nexus 5 from CyanogenMod 13 to LineageOS 14.1 connection with my jabber account is not possible anymore because of a certificate verification error. Same happens on a stock rom on a Nexus 9.

#### General information

* **Version:** 1.16.2
* **Device:** Google Nexus 5, Google Nexus 9
* **Android Version:** LineageOS 14.1 on Nexus 5, Android 7.1.1 on Nexus 9
* **Server name:** jabber.fsfe.org
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Connect to jabber.fsfe.org

#### Expected result

I expect to successfully connect to the server, but instead I get a security error. The TLS certificate verification failed, see debug output. Opening fsfe.org in browser app with https works without problems. 

#### Debug output

````
02-20 22:48:49.363 13499 14189 D conversations: zwobbl@jabber.fsfe.org: connecting
02-20 22:48:49.367 13499 14189 D conversations: used lollipop variant to discover dns servers in 1 networks
02-20 22:48:49.368 13499 14189 D conversations: using dns server: 192.168.77.254 to look up jabber.fsfe.org
02-20 22:48:49.395 13499 14189 D conversations: zwobbl@jabber.fsfe.org: using values from dns jabber.fsfe.org[[2001:aa8:ffed:f5f3:0:0:0:179]]:5222 tls: false
02-20 22:48:49.397 13499 14189 D conversations: zwobbl@jabber.fsfe.org: Network is unreachable(java.net.ConnectException)
02-20 22:48:49.397 13499 14189 D conversations: zwobbl@jabber.fsfe.org: using values from dns jabber.fsfe.org[217.69.89.179]:5222 tls: false
02-20 22:48:50.232 13499 14189 W System.err: javax.net.ssl.SSLPeerUnverifiedException: No peer certificate
02-20 22:48:50.232 13499 14189 W System.err:    at com.android.org.conscrypt.SSLNullSession.getPeerCertificates(SSLNullSession.java:104)
02-20 22:48:50.232 13499 14189 W System.err:    at de.duenndns.ssl.MemorizingTrustManager$MemorizingHostnameVerifier.verify(MemorizingTrustManager.java:804)
02-20 22:48:50.232 13499 14189 W System.err:    at de.duenndns.ssl.MemorizingTrustManager$MemorizingHostnameVerifier.verify(MemorizingTrustManager.java:825)
02-20 22:48:50.232 13499 14189 W System.err:    at eu.siacs.conversations.xmpp.XmppConnection.switchOverToTls(XmppConnection.java:798)
02-20 22:48:50.232 13499 14189 W System.err:    at eu.siacs.conversations.xmpp.XmppConnection.processStream(XmppConnection.java:513)
02-20 22:48:50.232 13499 14189 W System.err:    at eu.siacs.conversations.xmpp.XmppConnection.connect(XmppConnection.java:400)
02-20 22:48:50.232 13499 14189 W System.err:    at eu.siacs.conversations.xmpp.XmppConnection.run(XmppConnection.java:502)
02-20 22:48:50.232 13499 14189 W System.err:    at java.lang.Thread.run(Thread.java:761)
02-20 22:48:50.232 13499 14189 D conversations: zwobbl@jabber.fsfe.org: TLS certificate verification failed
02-20 22:48:50.232 13499 14189 D conversations: zwobbl@jabber.fsfe.org: error connecting account. try again in 32s for the 2 time
````

**Comment by zwobbl** [comment]
Looks like a server configuration issue because it works now without any changes.
