### ISSUE TITLE
Conversations crash

### ISSUE THREAD

**Issue by nekoswag** [siacs/Conversations#2467]
#### General information

* **Version:** 1.18.2
* **Device:** LG G4 h815
* **Android Version:** Android 6.0, Kernel 3.10.84
* **Server name:** self hosted
* **Server software:** Prosod 0.9.12
* **Installed server modules:** roster, saslauth, tls, dialback, disco, private, vcard, version, uptime, time, ping, pep, register, admin_adhoc, posix, blocking, smacks, carbons, mam, csi, http, http_upload, muc
* **Conversations source:** F-Droid

#### Steps to reproduce

I don't know how to reproduce it since it never happened before and I didn't do anything unusual when it crashed.

#### autogenerated log

Version: 1.18.2
Last Update: 2017-04-25
SHA-1: 20:ab:18:ba:4d:49:1d:f1:b7:bf:50:51:be:1f:e2:6e:b7:56:27:73

java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.app.Activity.getApplicationContext()' on a null object reference
	at eu.siacs.conversations.ui.ConversationFragment.reInit(ConversationFragment.java:908)
	at eu.siacs.conversations.ui.ConversationActivity.onBackendConnected(ConversationActivity.java:1228)
	at eu.siacs.conversations.ui.XmppActivity$3.onServiceConnected(XmppActivity.java:187)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1267)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1284)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5525)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)

**Comment by iNPUTmice** [comment]
This has been fixed in 1.18.3 which was released two days ago.
