### ISSUE TITLE
register fail

### ISSUE THREAD

**Issue by wongainia** [siacs/Conversations#2523]
de.measite.minidns.dnssec.DNSSECValidationFailedException: Validation of request to xmpp.conversations.im.	IN	AAAA failed: NSECs must always match to a SOA
                                                                          at de.measite.minidns.dnssec.DNSSECClient.verifyNsec(DNSSECClient.java:212)
                                                                          at de.measite.minidns.dnssec.DNSSECClient.verify(DNSSECClient.java:148)
                                                                          at de.measite.minidns.dnssec.DNSSECClient.performVerification(DNSSECClient.java:106)
                                                                          at de.measite.minidns.dnssec.DNSSECClient.queryDnssec(DNSSECClient.java:94)
                                                                          at de.measite.minidns.hla.DnssecResolverApi.resolve(DnssecResolverApi.java:64)
                                                                          at de.measite.minidns.hla.ResolverApi.resolve(ResolverApi.java:40)
                                                                          at eu.siacs.conversations.utils.Resolver.resolveIp(Resolver.java:79)
                                                                          at eu.siacs.conversations.utils.Resolver.resolveSrv(Resolver.java:65)

**Comment by iNPUTmice** [comment]
Please don't just post random stack traces. The might be merely warnings and don't mean anything like in this case.
