### ISSUE TITLE
issue while connecting for Nougut Devices belw is my log

### ISSUE THREAD

**Issue by Nits2407** [siacs/Conversations#2534]
General information

    Version: eg 1.12.2
    Device: Honor 6X
    Android Version: Android 7.0 
    Server software: ejabberd 16.04

java.lang.VerifyError: org/whispersystems/curve25519/java/fe_mul
at org.whispersystems.curve25519.java.ge_madd.ge_madd(ge_madd.java:65)
at org.whispersystems.curve25519.java.ge_scalarmult_base.ge_scalarmult_base(ge_scalarmult_base.java:96)
at org.whispersystems.curve25519.java.curve_sigs.curve25519_keygen(curve_sigs.java:30)
at org.whispersystems.curve25519.BaseJavaCurve25519Provider.generatePublicKey(BaseJavaCurve25519Provider.java:50)
at org.whispersystems.curve25519.JavaCurve25519Provider.generatePublicKey(JavaCurve25519Provider.java:8)
at org.whispersystems.curve25519.OpportunisticCurve25519Provider.generatePublicKey(OpportunisticCurve25519Provider.java:27)
at org.whispersystems.curve25519.Curve25519.generateKeyPair(Curve25519.java:70)
at org.whispersystems.libaxolotl.ecc.Curve.generateKeyPair(Curve.java:35)
at eu.siacs.conversations.crypto.axolotl.SQLiteAxolotlStore.generateIdentityKeyPair(SQLiteAxolotlStore.java:62)
at eu.siacs.conversations.crypto.axolotl.SQLiteAxolotlStore.loadIdentityKeyPair(SQLiteAxolotlStore.java:99)
at eu.siacs.conversations.crypto.axolotl.SQLiteAxolotlStore.getIdentityKeyPair(SQLiteAxolotlStore.java:157)
at eu.siacs.conversations.crypto.axolotl.AxolotlService$4.onIqPacketReceived(AxolotlService.java:390)
at eu.siacs.conversations.xmpp.XmppConnection.processIq(XmppConnection.java:500)
at eu.siacs.conversations.xmpp.XmppConnection.processStream(XmppConnection.java:382)
at eu.siacs.conversations.xmpp.XmppConnection.processStream(XmppConnection.java:294)
at eu.siacs.conversations.xmpp.XmppConnection.switchOverToTls(XmppConnection.java:564)
at eu.siacs.conversations.xmpp.XmppConnection.processStream(XmppConnection.java:280)
at eu.siacs.conversations.xmpp.XmppConnection.connect(XmppConnection.java:220)
at eu.siacs.conversations.xmpp.XmppConnection.run(XmppConnection.java:267)
at java.lang.Thread.run(Thread.java:856)

**Comment by iNPUTmice** [comment]
Please fill in the issue template with Device, ROM version, Conversations version etc. We have that template for a reason.

**Comment by iNPUTmice** [comment]
No response from OP. Closing.
