### ISSUE TITLE
java.lang.NullPointerException: iv == null

### ISSUE THREAD

**Issue by crypto-universe** [siacs/Conversations#2595]
#### General information

* **Version:** since 1.20.0-beta.2 (dd5e3212471d0e0c8aa2dcbae13adeb4289de388) till last commit on master (d348780dfc2e0e4bd94dbaf045f474d0f13bc24a). Worked fine on 1.18.5. Didn't check commits in between.
Built with minSdkVersion=23
* **Device:** Lenovo C2 Power (= Lenovo K10a40)
* **Android Version:** Android 6.0
* **Server name:** chatme.im
* **Server software:** have no idea
* **Installed server modules:** don't know
* **Conversations source:** self build (see commit numbers above)

#### Steps to reproduce

1. Set OTR encryption.
2. Send any picture
3. App crashes a few times in a row.
4. Picture is not delivered.

Sometimes crashes on the text messages, but after recovery text is encrypted and delivered.

#### Expected result

I see crash, but should work smoothly.

#### Debug output
Version: 1.20.0-beta.2
Last Update: 2017-08-17
SHA-1: 68:00:57:fb:c_d:26:68:49:7a:98:5e:67:b9:70:98:0e:da:4c:92:e8

java.lang.NullPointerException: iv == null
at javax.crypto.spec.IvParameterSpec.(IvParameterSpec.java:45)
at eu.siacs.conversations.services.AbstractConnectionManager.createInputStream(AbstractConnectionManager.java:80)
at eu.siacs.conversations.xmpp.jingle.JingleConnection.sendInitRequest(JingleConnection.java:490)
at eu.siacs.conversations.xmpp.jingle.JingleConnection.access$1700(JingleConnection.java:43)
at eu.siacs.conversations.xmpp.jingle.JingleConnection$5$1.failed(JingleConnection.java:305)
at eu.siacs.conversations.xmpp.jingle.JingleSocks5Transport$1.run(JingleSocks5Transport.java:80)
at java.lang.Thread.run(Thread.java:818)

**Comment by crypto-universe** [comment]
Also these apks (from dd5e321 and d348780 commits) crashes on another device:
**Device:** Xiaomi Redmi 4x 
**Android Version:** Android 6.0.1 MMB29M + MIUI Global 8.2.10.0 Stable (MAMMIEA)
Everything else is the same, including server.

**Comment by iNPUTmice** [comment]
Please switch to OMEMO if you can.

**Comment by licaon-kter** [comment]
@crypto-universe F-Droid builds for 1.19.5 or 1.20.0 work or fail? (so we can exclude your build system)

**Comment by crypto-universe** [comment]
Fix solved my problem. Pictures can be sent and received. Thanks everybody for help!
