### ISSUE TITLE
java.security.cert.CertificateException: java.security.cert.CertPathValidatorException:

### ISSUE THREAD

**Issue by ananth10** [siacs/Conversations#2600]
I am seeing the error regarding "Certificate" .  for the reference i have pased the Logcat. please check it

and let me know where i was wrong. Thank you in advance.

**LogCat**

```
08-28 19:00:59.064 9934-9934/com.probbe E/ViewRootImpl: sendUserActionEvent() mView == null
08-28 19:00:59.067 9934-10120/com.probbe V/FA: Recording user engagement, ms: 26032
08-28 19:00:59.068 9934-10120/com.probbe V/FA: Using measurement service
08-28 19:00:59.068 9934-10120/com.probbe V/FA: Connecting to remote service
08-28 19:00:59.072 9934-10120/com.probbe V/FA: Activity paused, time: 92208514
08-28 19:00:59.074 9934-10120/com.probbe D/FA: Logging event (FE): user_engagement(_e), Bundle[{firebase_event_origin(_o)=auto, engagement_time_msec(_et)=26032, firebase_screen_class(_sc)=LoginActivity, firebase_screen_id(_si)=-2120932495814122346}]
08-28 19:00:59.082 9934-10120/com.probbe V/FA: Using measurement service
08-28 19:00:59.082 9934-10120/com.probbe V/FA: Connection attempt already in progress
08-28 19:00:59.248 9934-9934/com.probbe V/FA: onActivityCreated
08-28 19:00:59.425 9934-9934/com.probbe E/TextView: Could not get typeface: null
08-28 19:00:59.444 9934-10120/com.probbe V/FA: Using measurement service
08-28 19:00:59.444 9934-10120/com.probbe V/FA: Connection attempt already in progress
08-28 19:00:59.444 9934-10120/com.probbe V/FA: Activity resumed, time: 92208890
08-28 19:00:59.446 9934-10120/com.probbe D/FA: Logging event (FE): screen_view(_vs), Bundle[{firebase_event_origin(_o)=auto, firebase_previous_class(_pc)=LoginActivity, firebase_previous_id(_pi)=-2120932495814122346, firebase_screen_class(_sc)=EditAccountActivity, firebase_screen_id(_si)=-2120932495814122345}]
08-28 19:00:59.452 9934-10120/com.probbe V/FA: Using measurement service
08-28 19:00:59.452 9934-10120/com.probbe V/FA: Connection attempt already in progress
08-28 19:00:59.461 9934-9934/com.probbe D/ViewRootImpl@c0aa5b1[EditAccountActivity]: ThreadedRenderer.create() translucent=false
08-28 19:00:59.464 9934-9934/com.probbe D/InputTransport: Input channel constructed: fd=88
08-28 19:00:59.464 9934-9934/com.probbe D/ViewRootImpl@c0aa5b1[EditAccountActivity]: setView = DecorView@6eaaa96[EditAccountActivity] touchMode=true
08-28 19:00:59.465 9934-10120/com.probbe D/FA: Connected to remote service
08-28 19:00:59.465 9934-10120/com.probbe V/FA: Processing queued up service tasks: 4
08-28 19:00:59.467 9934-9934/com.probbe D/ViewRootImpl@c0aa5b1[EditAccountActivity]: dispatchAttachedToWindow
08-28 19:00:59.484 9934-9934/com.probbe D/ViewRootImpl@c0aa5b1[EditAccountActivity]: Relayout returned: oldFrame=[0,0][0,0] newFrame=[0,0][1440,2560] result=0x27 surface={isValid=true 487606544384} surfaceGenerationChanged=true
08-28 19:00:59.484 9934-9934/com.probbe D/ViewRootImpl@c0aa5b1[EditAccountActivity]: mHardwareRenderer.initialize() mSurface={isValid=true 487606544384} hwInitialized=true
08-28 19:00:59.506 9934-10168/com.probbe D/mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000,  [1440x2560]-format:1
08-28 19:00:59.701 9934-9934/com.probbe I/MemorizingTrustManager: getAppKeyStore(/data/user/0/com.probbe/app_KeyStore/KeyStore.bks) - file does not exist
08-28 19:00:59.702 9934-9934/com.probbe D/conversations: initializing database...
08-28 19:00:59.710 9934-9934/com.probbe D/conversations: restoring accounts...
08-28 19:00:59.739 9934-9934/com.probbe D/conversations: restoring conversations...
08-28 19:00:59.740 9934-9934/com.probbe D/conversations: finished restoring conversations in 1ms
08-28 19:00:59.742 9934-12935/com.probbe D/conversations: restoring roster...
08-28 19:00:59.744 9934-12935/com.probbe D/conversations: restoring messages...
08-28 19:00:59.744 9934-12935/com.probbe D/conversations: update unread count to 0
08-28 19:00:59.750 9934-12907/com.probbe D/conversations: start merging phone contacts with roster
08-28 19:00:59.750 9934-12907/com.probbe D/conversations: finished merging phone contacts
08-28 19:00:59.779 9934-12935/com.probbe D/conversations: finished restoring messages in 35ms
08-28 19:00:59.785 9934-9934/com.probbe D/conversations: schedule next idle ping
08-28 19:00:59.864 9934-9934/com.probbe D/ViewRootImpl@c0aa5b1[EditAccountActivity]: MSG_RESIZED_REPORT: ci=Rect(0, 96 - 0, 0) vi=Rect(0, 96 - 0, 0) or=1
08-28 19:00:59.864 9934-9934/com.probbe D/ViewRootImpl@c0aa5b1[EditAccountActivity]: MSG_WINDOW_FOCUS_CHANGED 1
08-28 19:00:59.864 9934-9934/com.probbe D/ViewRootImpl@c0aa5b1[EditAccountActivity]: mHardwareRenderer.initializeIfNeeded()#2 mSurface={isValid=true 487606544384}
08-28 19:00:59.868 9934-9934/com.probbe D/SEM_CLIP_SemClipboardManager: isCocktailBarDisplayed : false
08-28 19:00:59.869 9934-9934/com.probbe D/SEM_CLIP_SemClipboardManager: isCocktailBarDisplayed : false
08-28 19:00:59.869 9934-9934/com.probbe D/SEM_CLIP_SemClipboardManager: isCocktailBarDisplayed : false
08-28 19:00:59.870 9934-9934/com.probbe D/SEM_CLIP_SemClipboardManager: isCocktailBarDisplayed : false
08-28 19:00:59.882 9934-9934/com.probbe D/SEM_CLIP_SemClipboardManager: isCocktailBarDisplayed : false
08-28 19:00:59.882 9934-9934/com.probbe V/InputMethodManager: Starting input: tba=android.view.inputmethod.EditorInfo@ba1571e nm : com.probbe ic=null
08-28 19:00:59.883 9934-9934/com.probbe I/InputMethodManager: [IMM] startInputInner - mService.startInputOrWindowGainedFocus
08-28 19:00:59.918 9934-9934/com.probbe D/InputTransport: Input channel constructed: fd=104
08-28 19:00:59.918 9934-9934/com.probbe D/InputTransport: Input channel destroyed: fd=84
08-28 19:00:59.920 9934-9934/com.probbe D/conversations: app switched into foreground
08-28 19:00:59.949 9934-9934/com.probbe W/IInputConnectionWrapper: finishComposingText on inactive InputConnection
08-28 19:00:59.957 9934-9934/com.probbe D/ViewRootImpl@1cc35f3[LoginActivity]: mHardwareRenderer.destroy()#1
08-28 19:00:59.966 9934-9934/com.probbe D/ViewRootImpl@1cc35f3[LoginActivity]: Relayout returned: oldFrame=[0,0][1440,2560] newFrame=[0,0][1440,2560] result=0x5 surface={isValid=false 0} surfaceGenerationChanged=true
08-28 19:01:00.365 9934-9934/com.probbe D/ViewRootImpl@1cc35f3[LoginActivity]: mHardwareRenderer.destroy()#4
08-28 19:01:00.365 9934-9934/com.probbe D/ViewRootImpl@1cc35f3[LoginActivity]: dispatchDetachedFromWindow
08-28 19:01:00.381 9934-9934/com.probbe D/InputTransport: Input channel destroyed: fd=96
08-28 19:01:00.434 9934-9934/com.probbe I/System.out: test123 Jid :Saratha_20@probbe.co.uk
08-28 19:01:00.467 9934-9934/com.probbe I/System.out: test123 registerNewAccount :null
08-28 19:01:00.510 9934-9934/com.probbe I/conversations: AxolotlService (saratha_20@probbe.co.uk): Could not retrieve axolotl registration id for account saratha_20@probbe.co.uk/mobile
08-28 19:01:00.511 9934-9934/com.probbe I/conversations: AxolotlService : Generating axolotl registration ID...
08-28 19:01:00.514 9934-9934/com.probbe W/conversations: AxolotlService (saratha_20@probbe.co.uk): Could not retrieve current prekey id for account saratha_20@probbe.co.uk/mobile
08-28 19:01:00.544 9934-9934/com.probbe I/System.out: test123 Jid :Saratha_20@probbe.co.uk
08-28 19:01:00.544 9934-9934/com.probbe I/System.out: test123 numericPort :5222
08-28 19:01:00.544 9934-9934/com.probbe I/System.out: test123 hostname :null
08-28 19:01:00.545 9934-9934/com.probbe I/System.out: test123 password :Atom123456
08-28 19:01:00.545 9934-9934/com.probbe I/System.out: test123 registerNewAccount :false
08-28 19:01:00.570 9934-13063/com.probbe D/conversations: saratha_20@probbe.co.uk: socket was null during force close
08-28 19:01:00.570 9934-13063/com.probbe D/conversations: saratha_20@probbe.co.uk: connecting
08-28 19:01:01.045 9934-9948/com.probbe I/art: Do partial code cache collection, code=52KB, data=60KB
08-28 19:01:01.047 9934-9948/com.probbe I/art: After code cache collection, code=50KB, data=59KB
08-28 19:01:01.047 9934-9948/com.probbe I/art: Increasing code cache capacity to 256KB
08-28 19:01:04.495 9934-10120/com.probbe V/FA: Inactivity, disconnecting from the service
08-28 19:01:22.913 9934-9934/com.probbe D/ViewRootImpl@c0aa5b1[EditAccountActivity]: ViewPostImeInputStage processPointer 0
08-28 19:01:23.019 9934-9934/com.probbe D/ViewRootImpl@c0aa5b1[EditAccountActivity]: ViewPostImeInputStage processPointer 1
08-28 19:01:36.440 9934-13063/com.probbe D/conversations: Resolver: [Result{ip='35.177.219.83', hostame='probbe.co.uk', port=5222, directTls=false, authenticated=false, priority=0}, Result{ip='null', hostame='probbe.co.uk', port=5222, directTls=false, authenticated=false, priority=0}]
08-28 19:01:36.443 9934-13063/com.probbe D/conversations: saratha_20@probbe.co.uk: using values from dns probbe.co.uk/35.177.219.83:5222 tls: false
08-28 19:01:37.522 9934-13063/com.probbe D/mtm: downloading json for probbe.co.uk from https://probbe.co.uk/.well-known/posh/xmpp-client.json
08-28 19:01:37.526 9934-13063/com.probbe I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
08-28 19:01:37.527 9934-13063/com.probbe I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
08-28 19:01:37.798 9934-13063/com.probbe D/mtm: error fetching posh Connection refused
08-28 19:01:37.798 9934-13063/com.probbe W/System.err: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
08-28 19:01:37.805 9934-13063/com.probbe W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:546)
08-28 19:01:37.805 9934-13063/com.probbe W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:427)
08-28 19:01:37.805 9934-13063/com.probbe W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:387)
08-28 19:01:37.805 9934-13063/com.probbe W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:273)
08-28 19:01:37.805 9934-13063/com.probbe W/System.err:     at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:113)
08-28 19:01:37.805 9934-13063/com.probbe W/System.err:     at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:87)
08-28 19:01:37.806 9934-13063/com.probbe W/System.err:     at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:116)
08-28 19:01:37.806 9934-13063/com.probbe W/System.err:     at com.probbe.chat.memorizingtrustmanager.MemorizingTrustManager.checkCertTrusted(MemorizingTrustManager.java:426)
08-28 19:01:37.806 9934-13063/com.probbe W/System.err:     at com.probbe.chat.memorizingtrustmanager.MemorizingTrustManager$InteractiveMemorizingTrustManager.checkServerTrusted(MemorizingTrustManager.java:893)
08-28 19:01:37.806 9934-13063/com.probbe W/System.err:     at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:182)
08-28 19:01:37.806 9934-13063/com.probbe W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:617)
08-28 19:01:37.806 9934-13063/com.probbe W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
08-28 19:01:37.806 9934-13063/com.probbe W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:364)
08-28 19:01:37.806 9934-13063/com.probbe W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.waitForHandshake(OpenSSLSocketImpl.java:713)
08-28 19:01:37.806 9934-13063/com.probbe W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.getSession(OpenSSLSocketImpl.java:877)
08-28 19:01:37.806 9934-13063/com.probbe W/System.err:     at com.probbe.chat.xmpp.XmppConnection.switchOverToTls(XmppConnection.java:826)
08-28 19:01:37.807 9934-13063/com.probbe W/System.err:     at com.probbe.chat.xmpp.XmppConnection.processStream(XmppConnection.java:521)
08-28 19:01:37.807 9934-13063/com.probbe W/System.err:     at com.probbe.chat.xmpp.XmppConnection.connect(XmppConnection.java:419)
08-28 19:01:37.807 9934-13063/com.probbe W/System.err:     at com.probbe.chat.xmpp.XmppConnection.run(XmppConnection.java:510)
08-28 19:01:37.807 9934-13063/com.probbe W/System.err:     at java.lang.Thread.run(Thread.java:762)
08-28 19:01:37.807 9934-13063/com.probbe W/System.err: Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
08-28 19:01:37.807 9934-13063/com.probbe W/System.err: 	... 20 more
08-28 19:01:37.889 9934-9934/com.probbe D/ViewRootImpl@c0aa5b1[EditAccountActivity]: MSG_WINDOW_FOCUS_CHANGED 0
08-28 19:01:37.892 9934-9934/com.probbe D/SEM_CLIP_SemClipboardManager: isCocktailBarDisplayed : false
08-28 19:01:37.892 9934-9934/com.probbe D/SEM_CLIP_SemClipboardManager: isCocktailBarDisplayed : false
08-28 19:01:37.892 9934-9934/com.probbe D/SEM_CLIP_SemClipboardManager: isCocktailBarDisplayed : false
08-28 19:01:37.892 9934-9934/com.probbe D/SEM_CLIP_SemClipboardManager: isCocktailBarDisplayed : false
08-28 19:01:37.892 9934-9934/com.probbe D/SEM_CLIP_SemClipboardManager: isCocktailBarDisplayed : false
08-28 19:01:37.902 9934-15620/com.probbe V/FA: Recording user engagement, ms: 38459
08-28 19:01:37.902 9934-15620/com.probbe V/FA: Using measurement service
08-28 19:01:37.903 9934-15620/com.probbe V/FA: Connecting to remote service
08-28 19:01:37.906 9934-15620/com.probbe V/FA: Activity paused, time: 92247348
08-28 19:01:37.908 9934-15620/com.probbe D/FA: Logging event (FE): user_engagement(_e), Bundle[{firebase_event_origin(_o)=auto, engagement_time_msec(_et)=38459, firebase_screen_class(_sc)=EditAccountActivity, firebase_screen_id(_si)=-2120932495814122345}]
08-28 19:01:37.920 9934-15620/com.probbe V/FA: Using measurement service
08-28 19:01:37.920 9934-15620/com.probbe V/FA: Connection attempt already in progress
08-28 19:01:37.951 9934-9934/com.probbe V/FA: onActivityCreated
08-28 19:01:38.012 9934-15620/com.probbe V/FA: Using measurement service
08-28 19:01:38.012 9934-15620/com.probbe V/FA: Connection attempt already in progress
08-28 19:01:38.012 9934-15620/com.probbe V/FA: Activity resumed, time: 92247458
08-28 19:01:38.015 9934-15620/com.probbe D/FA: Logging event (FE): screen_view(_vs), Bundle[{firebase_event_origin(_o)=auto, firebase_previous_class(_pc)=EditAccountActivity, firebase_previous_id(_pi)=-2120932495814122345, firebase_screen_class(_sc)=MemorizingActivity, firebase_screen_id(_si)=-2120932495814122344}]
08-28 19:01:38.028 9934-15620/com.probbe V/FA: Using measurement service
08-28 19:01:38.028 9934-15620/com.probbe V/FA: Connection attempt already in progress
08-28 19:01:38.034 9934-15620/com.probbe D/FA: Connected to remote service
08-28 19:01:38.034 9934-15620/com.probbe V/FA: Processing queued up service tasks: 4
08-28 19:01:38.069 9934-15620/com.probbe V/FA: Screen exposed for less than 1000 ms. Event not sent. time: 58
08-28 19:01:38.070 9934-15620/com.probbe V/FA: Activity paused, time: 92247481
08-28 19:01:38.071 9934-15620/com.probbe V/FA: Activity resumed, time: 92247511
08-28 19:01:38.071 9934-9934/com.probbe I/conversations: AxolotlService (saratha_20@probbe.co.uk): Could not retrieve own IdentityKeyPair
08-28 19:01:38.071 9934-9934/com.probbe I/conversations: AxolotlService : Generating axolotl IdentityKeyPair...
08-28 19:01:38.075 9934-15620/com.probbe D/FA: Logging event (FE): screen_view(_vs), Bundle[{firebase_event_origin(_o)=auto, firebase_previous_class(_pc)=MemorizingActivity, firebase_previous_id(_pi)=-2120932495814122344, firebase_screen_class(_sc)=EditAccountActivity, firebase_screen_id(_si)=-2120932495814122345}]
08-28 19:01:38.147 9934-9934/com.probbe D/ViewRootImpl@c0aa5b1[EditAccountActivity]: MSG_WINDOW_FOCUS_CHANGED 1
08-28 19:01:38.147 9934-9934/com.probbe D/ViewRootImpl@c0aa5b1[EditAccountActivity]: mHardwareRenderer.initializeIfNeeded()#2 mSurface={isValid=true 487606544384}
08-28 19:01:38.147 9934-9934/com.probbe D/SEM_CLIP_SemClipboardManager: isCocktailBarDisplayed : false
08-28 19:01:38.147 9934-9934/com.probbe D/SEM_CLIP_SemClipboardManager: isCocktailBarDisplayed : false
08-28 19:01:38.147 9934-9934/com.probbe D/SEM_CLIP_SemClipboardManager: isCocktailBarDisplayed : false
08-28 19:01:38.148 9934-9934/com.probbe D/SEM_CLIP_SemClipboardManager: isCocktailBarDisplayed : false
08-28 19:01:38.148 9934-9934/com.probbe D/SEM_CLIP_SemClipboardManager: isCocktailBarDisplayed : false
08-28 19:01:38.158 9934-9934/com.probbe D/ViewRootImpl@c0aa5b1[EditAccountActivity]: Relayout returned: oldFrame=[0,0][1440,2560] newFrame=[0,0][1440,2560] result=0x1 surface={isValid=true 487606544384} surfaceGenerationChanged=false
08-28 19:01:38.297 9934-13063/com.probbe D/XmppDomainVerifier: domain probbe.co.uk matched probbe.co.uk
08-28 19:01:38.297 9934-13063/com.probbe D/XmppDomainVerifier: accepted CN in self signed cert as work around for probbe.co.uk
08-28 19:01:38.299 9934-13063/com.probbe D/conversations: saratha_20@probbe.co.uk: TLS connection established
08-28 19:01:38.525 9934-13063/com.probbe D/conversations: saratha_20@probbe.co.uk/phone: Authenticating with SCRAM-SHA-1
08-28 19:01:38.768 9934-13063/com.probbe D/conversations: saratha_20@probbe.co.uk: error connecting account. reconnecting now. lowPingTimeout=false
08-28 19:01:38.773 9934-15646/com.probbe D/conversations: saratha_20@probbe.co.uk: connecting
08-28 19:01:38.779 9934-13063/com.probbe D/conversations: saratha_20@probbe.co.uk: not force closing socket and releasing wake lock (is held=false) because thread was interrupted
08-28 19:01:43.108 9934-15620/com.probbe V/FA: Inactivity, disconnecting from the service
08-28 19:01:46.908 9934-9934/com.probbe D/ViewRootImpl@c0aa5b1[EditAccountActivity]: ViewPostImeInputStage processPointer 0
08-28 19:01:47.110 9934-9934/com.probbe D/ViewRootImpl@c0aa5b1[EditAccountActivity]: ViewPostImeInputStage processPointer 1
08-28 19:02:02.733 9934-9954/com.probbe I/art: Background sticky concurrent mark sweep GC freed 114864(7MB) AllocSpace objects, 33(948KB) LOS objects, 9% free, 87MB/97MB, paused 486us total 124.671ms
08-28 19:02:11.637 9934-9934/com.probbe D/ViewRootImpl@c0aa5b1[EditAccountActivity]: ViewPostImeInputStage processPointer 0
08-28 19:02:11.694 9934-9934/com.probbe D/ViewRootImpl@c0aa5b1[EditAccountActivity]: ViewPostImeInputStage processPointer 1
08-28 19:02:19.174 9934-15646/com.probbe D/conversations: Resolver: [Result{ip='35.177.219.83', hostame='probbe.co.uk', port=5222, directTls=false, authenticated=false, priority=0}, Result{ip='null', hostame='probbe.co.uk', port=5222, directTls=false, authenticated=false, priority=0}]
08-28 19:02:19.175 9934-15646/com.probbe D/conversations: saratha_20@probbe.co.uk: using values from dns probbe.co.uk/35.177.219.83:5222 tls: false
08-28 19:02:20.513 9934-15646/com.probbe D/XmppDomainVerifier: domain probbe.co.uk matched probbe.co.uk
08-28 19:02:20.513 9934-15646/com.probbe D/XmppDomainVerifier: accepted CN in self signed cert as work around for probbe.co.uk
08-28 19:02:20.526 9934-15646/com.probbe D/conversations: saratha_20@probbe.co.uk: TLS connection established
08-28 19:02:20.798 9934-15646/com.probbe D/conversations: saratha_20@probbe.co.uk/phone: Authenticating with SCRAM-SHA-1
08-28 19:02:21.017 9934-15646/com.probbe D/conversations: saratha_20@probbe.co.uk: error connecting account. reconnecting now. lowPingTimeout=false
08-28 19:02:21.022 9934-17055/com.probbe D/conversations: saratha_20@probbe.co.uk: connecting
08-28 19:02:21.075 9934-15646/com.probbe D/conversations: saratha_20@probbe.co.uk: not force closing socket and releasing wake lock (is held=false) because thread was interrupted
08-28 19:02:41.658 9934-9934/com.probbe V/InputMethodManager: Starting input: tba=android.view.inputmethod.EditorInfo@be80b8b nm : com.probbe ic=null
08-28 19:02:41.658 9934-9934/com.probbe I/InputMethodManager: [IMM] startInputInner - mService.startInputOrWindowGainedFocus
08-28 19:02:41.664 9934-9934/com.probbe D/InputTransport: Input channel constructed: fd=109
08-28 19:02:41.664 9934-9934/com.probbe D/InputTransport: Input channel destroyed: fd=104
08-28 19:02:42.126 9934-17742/com.probbe V/FA: Recording user engagement, ms: 64062
08-28 19:02:42.127 9934-17742/com.probbe V/FA: Using measurement service
08-28 19:02:42.128 9934-17742/com.probbe V/FA: Connecting to remote service
08-28 19:02:42.134 9934-17742/com.probbe V/FA: Activity paused, time: 92311572
08-28 19:02:42.142 9934-17742/com.probbe D/FA: Logging event (FE): user_engagement(_e), Bundle[{firebase_event_origin(_o)=auto, engagement_time_msec(_et)=64062, firebase_screen_class(_sc)=EditAccountActivity, firebase_screen_id(_si)=-2120932495814122345}]
08-28 19:02:42.159 9934-17742/com.probbe V/FA: Using measurement service
08-28 19:02:42.159 9934-17742/com.probbe V/FA: Connection attempt already in progress
08-28 19:02:42.262 9934-17742/com.probbe D/FA: Connected to remote service
08-28 19:02:42.262 9934-17742/com.probbe V/FA: Processing queued up service tasks: 2
08-28 19:02:42.269 9934-9934/com.probbe D/conversations: app switched into background
```

**Comment by iNPUTmice** [comment]
If you are looking for free support please use our conference (group chat). This is an issue tracker reserved for bug reports only.
