### ISSUE TITLE
Message missing required fields:

### ISSUE THREAD

**Issue by anrdspring** [siacs/Conversations#2699]
* **Version:** 1.22.0
* **Device:** Samsung S7 edge
* **Android Version:** Android 7.0
* **Server name:**  conversations.im
* **Conversations source:** Github Project

FATAL EXCEPTION: Thread-10
                  Process: eu.siacs.conversations, PID: 6693
                  com.google.protobuf.UninitializedMessageException: Message missing required fields: 
                      at com.google.protobuf.AbstractMessage$Builder.newUninitializedMessageException(AbstractMessage.java:770)
                      at org.whispersystems.libsignal.state.StorageProtos$IdentityKeyPairStructure$Builder.build(StorageProtos.java:8127)
                      at org.whispersystems.libsignal.IdentityKeyPair.serialize(IdentityKeyPair.java:53)
                      at eu.siacs.conversations.persistance.DatabaseBackend.storeOwnIdentityKeyPair(DatabaseBackend.java:1369)
                      at eu.siacs.conversations.crypto.axolotl.SQLiteAxolotlStore.loadIdentityKeyPair(SQLiteAxolotlStore.java:102)
                      at eu.siacs.conversations.crypto.axolotl.SQLiteAxolotlStore.getIdentityKeyPair(SQLiteAxolotlStore.java:160)
                      at eu.siacs.conversations.crypto.axolotl.AxolotlService$4.onIqPacketReceived(AxolotlService.java:643)
                      at eu.siacs.conversations.xmpp.XmppConnection.processIq(XmppConnection.java:790)
                      at eu.siacs.conversations.xmpp.XmppConnection.processStream(XmppConnection.java:670)
                      at eu.siacs.conversations.xmpp.XmppConnection.processStream(XmppConnection.java:538)
                      at eu.siacs.conversations.xmpp.XmppConnection.connect(XmppConnection.java:420)
                      at eu.siacs.conversations.xmpp.XmppConnection.run(XmppConnection.java:511)
                      at java.lang.Thread.run(Thread.java:762)

**Comment by licaon-kter** [comment]
What did you do exactly?

Older versions worked ok?

**Comment by anrdspring** [comment]
Actually I did't use older versions But Its Work Fine On Other Device like Motorola G3 And samsung s3.
But in samsung s7 (Android 7.0) after create new account app redirect me to app home page(Welcome screen with view pager) at that time app is crash.

**Comment by iNPUTmice** [comment]
Have you tried with the fdroid version or the playstore version? Maybe that's a build error.

**Comment by anrdspring** [comment]
No I din't. May be you are right because i change gradle versions. So is it possible that this error occurred because of changes in gradle version? I change version 2.3.3 to 2.2.2

**Comment by anrdspring** [comment]
Hello Sir, I also change the gradle version to 2.3.3 and build again but same issue comes again in Android 7.0(Samsung S7) though it works fine on android 6.0(Moto G3) and Android 5.0(Samsung S4) .Can You Please Help me solve this Problem?
Thank You.

**Comment by iNPUTmice** [comment]
Please try to F-Droid version.

**Comment by anrdspring** [comment]
Ok Sir, And Sir Actually I am new in this project and trying to understand xmpp protocol with android so is this app use smack android api to connect with xmpp server Or Any Other? 
Thank You For your quick response.
