### ISSUE TITLE
crash on start of 2.0.0-beta.2 (on android 4.3)

### ISSUE THREAD

**Issue by genofire** [siacs/Conversations#2922]
#### General information

* **Version:** 2.0.0-beta.2
* **Device:** Samsiung
* **Android Version:** Android 4.3 Stock
* **Server name:** self hosted
* **Server software:** prosody 0.10 (if known)
* **Installed server modules:** eg Stream Managment, CSI, MAM
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Start Conversation

#### Expected result

Running (or popup - that this android version is not supported any more)

#### Actual result

Crash

#### Debug output
````
W/dalvikvm(30775): threadid=1: thread exiting with uncaught exception (group=0x41a51700)
E/AndroidRuntime(30775): FATAL EXCEPTION: main
E/AndroidRuntime(30775): java.lang.NoClassDefFoundError: java.nio.charset.StandardCharsets
E/AndroidRuntime(30775): 	at rocks.xmpp.addr.FullJid.validateLength(FullJid.java:300)
E/AndroidRuntime(30775): 	at rocks.xmpp.addr.FullJid.<init>(FullJid.java:135)
E/AndroidRuntime(30775): 	at rocks.xmpp.addr.FullJid.<init>(FullJid.java:102)
E/AndroidRuntime(30775): 	at rocks.xmpp.addr.Jid$$CC.of$$STATIC$$(Unknown Source)
E/AndroidRuntime(30775): 	at eu.siacs.conversations.entities.Account.fromCursor(Account.java:283)
E/AndroidRuntime(30775): 	at eu.siacs.conversations.persistance.DatabaseBackend.getAccounts(DatabaseBackend.java:799)
E/AndroidRuntime(30775): 	at eu.siacs.conversations.persistance.DatabaseBackend.getAccounts(DatabaseBackend.java:772)
E/AndroidRuntime(30775): 	at eu.siacs.conversations.services.XmppConnectionService.onCreate(XmppConnectionService.java:967)
E/AndroidRuntime(30775): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2687)
E/AndroidRuntime(30775): 	at android.app.ActivityThread.access$1700(ActivityThread.java:159)
E/AndroidRuntime(30775): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1404)
E/AndroidRuntime(30775): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(30775): 	at android.os.Looper.loop(Looper.java:176)
E/AndroidRuntime(30775): 	at android.app.ActivityThread.main(ActivityThread.java:5419)
E/AndroidRuntime(30775): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(30775): 	at java.lang.reflect.Method.invoke(Method.java:525)
E/AndroidRuntime(30775): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
E/AndroidRuntime(30775): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
E/AndroidRuntime(30775): 	at dalvik.system.NativeStart.main(Native Method)
I/ActivityManager( 2353): Notify an ApplicationCrash

````
Not shown up in: `adb logcat -s conversations`

**Comment by genofire** [comment]
@SoyaLeaf nice, 
1. how could i move my omemo key?
2. was there not a option to disable possibility to install on older system?

**Comment by iNPUTmice** [comment]
> was there not a option to disable possibility to install on older system?

There is. And it is being used in 2.0.0 stable.
