### ISSUE TITLE
Sending images to people using other clients (Gajim in this case)

### ISSUE THREAD

**Issue by ijneb** [siacs/Conversations#2987]
Anytime I (or friends) use conversations to send images to people using other clients, it fails. The data transfer remains at 0% and even causes some error on Gajim. I know for sure that this also occurs when the other person is using Pidgin.

We were using omemo in this case, but it also happens without omemo. It also occurs with and without compression enabled.

Here's the Gajim error (it's on windows in this case):
```
## Versions
- OS: Windows 8.1
- GTK+ Version: 3.22.28
- PyGObject Version: 3.28.1
- python-nbxmpp Version: 0.6.4
- Gajim Version: 1.0.1

## Traceback
Traceback (most recent call last):
  File "C:/msys64/home/appveyor/gajim/win/_build_root/mingw32/lib/python3.6/site-packages/nbxmpp/dispatcher_nb.py", line 498, in dispatch
  File "C:/msys64/home/appveyor/gajim/win/_build_root/mingw32/lib/python3.6/site-packages/gajim/common/jingle.py", line 111, in _JingleCB
  File "C:/msys64/home/appveyor/gajim/win/_build_root/mingw32/lib/python3.6/site-packages/gajim/common/jingle_session.py", line 353, in on_stanza
  File "C:/msys64/home/appveyor/gajim/win/_build_root/mingw32/lib/python3.6/site-packages/gajim/common/jingle_session.py", line 528, in __on_session_initiate
IndexError: list index out of range
```

Here is a logcat dump of conversations stuff:
```
--------- beginning of main
--------- beginning of system
D/conversations(26408): onCreateView
D/conversations(26408): ConversationsOverviewFragment.onStart()
D/conversations(26408): ConversationsOverviewFragment.onResume()
D/conversations(26408): initializing database...
D/conversations(26408): restoring accounts...
D/conversations(26408): restoring conversations...
D/conversations(26408): finished restoring conversations in 4ms
D/conversations(26408): deleting messages that are older than 2018-04-24T04:14:23.356Z
D/conversations(26408): restoring roster...
D/conversations(26408): started foreground service
D/conversations(26408): update unread count to 0
D/conversations(26408): restoring messages...
D/conversations(26408): professor@autistici.org: socket was null during force close
D/conversations(26408): professor@autistici.org: connecting
D/conversations(26408): finished restoring messages in 44ms
D/conversations(26408): app switched into foreground
D/conversations(26408): start merging phone contacts with roster
D/conversations(26408): finished merging phone contacts
D/conversations(26408): ConversationsOverviewFragment.onPause()
D/conversations(26408): ConversationFragment.onAttach()
D/conversations(26408): reInit(hasExtras=true)
D/conversations(26408): trimming conversation
D/conversations(26408): Resolver: error resolving SRV with DNSSEC. Trying DNS instead.
D/conversations(26408): de.measite.minidns.dnssec.DNSSECValidationFailedException: Validation of 1 NSEC3 record failed: Signature is invalid.
D/conversations(26408): 	at de.measite.minidns.dnssec.Verifier.verify(Verifier.java:76)
D/conversations(26408): 	at de.measite.minidns.dnssec.DNSSECClient.verifySignedRecords(DNSSECClient.java:373)
D/conversations(26408): 	at de.measite.minidns.dnssec.DNSSECClient.verifySignatures(DNSSECClient.java:295)
D/conversations(26408): 	at de.measite.minidns.dnssec.DNSSECClient.verifyNsec(DNSSECClient.java:239)
D/conversations(26408): 	at de.measite.minidns.dnssec.DNSSECClient.verify(DNSSECClient.java:148)
D/conversations(26408): 	at de.measite.minidns.dnssec.DNSSECClient.performVerification(DNSSECClient.java:106)
D/conversations(26408): 	at de.measite.minidns.dnssec.DNSSECClient.queryDnssec(DNSSECClient.java:94)
D/conversations(26408): 	at de.measite.minidns.hla.DnssecResolverApi.resolveDnssecReliable(DnssecResolverApi.java:108)
D/conversations(26408): 	at eu.siacs.conversations.utils.Resolver.resolveWithFallback(Resolver.java:166)
D/conversations(26408): 	at eu.siacs.conversations.utils.Resolver.resolveWithFallback(Resolver.java:157)
D/conversations(26408): 	at eu.siacs.conversations.utils.Resolver.resolveSrv(Resolver.java:99)
D/conversations(26408): 	at eu.siacs.conversations.utils.Resolver.resolve(Resolver.java:58)
D/conversations(26408): 	at eu.siacs.conversations.xmpp.XmppConnection.connect(XmppConnection.java:311)
D/conversations(26408): 	at eu.siacs.conversations.xmpp.XmppConnection.run(XmppConnection.java:463)
D/conversations(26408): 	at java.lang.Thread.run(Thread.java:818)
D/conversations(26408): scrolledToBottomAndNoPending=true
D/conversations(26408): jump to first unread message
D/conversations(26408): AxolotlService (professor@autistici.org): Finding devices without session for benji@wusz.org
W/conversations(26408): AxolotlService (professor@autistici.org): Have no target devices in PEP!
D/conversations(26408): AxolotlService (professor@autistici.org): Finding devices without session for benji@wusz.org
W/conversations(26408): AxolotlService (professor@autistici.org): Have no target devices in PEP!
D/conversations(26408): app switched into background
D/conversations(26408): Resolver: [Result{ip='94.23.50.208', hostame='jabber.l.autistici.org', port=5222, directTls=false, authenticated=true, priority=10}, Result{ip='212.103.72.250', hostame='jabber.l.autistici.org', port=5222, directTls=false, authenticated=true, priority=10}, Result{ip='198.167.222.108', hostame='jabber.l.autistici.org', port=5222, directTls=false, authenticated=true, priority=10}, Result{ip='2a00:c38:11e:ffff::a020', hostame='jabber.l.autistici.org', port=5222, directTls=false, authenticated=true, priority=10}, Result{ip='2c0f:f930:0:4::108', hostame='jabber.l.autistici.org', port=5222, directTls=false, authenticated=true, priority=10}, Result{ip='2001:41d0:2:33d0::19', hostame='jabber.l.autistici.org', port=5222, directTls=false, authenticated=true, priority=10}]
D/conversations(26408): professor@autistici.org: using values from dns jabber.l.autistici.org/94.23.50.208:5222 tls: false
D/conversations(26408): professor@autistici.org: TLS connection established
D/conversations(26408): professor@autistici.org/Conversations.Pb3x: Authenticating with PLAIN
D/conversations(26408): professor@autistici.org: logged in
D/conversations(26408): ConversationsActivity.onActivityResult() - attaching image to conversations. CHOOSE_IMAGE
D/conversations(26408): copy image (content://com.android.providers.media.documents/document/image%3A145793) to private storage /storage/emulated/0/Conversations/Media/Conversations Images/8c4f8918-544a-45c8-bde8-743c8aee2c85.jpg
D/conversations(26408): reInit(hasExtras=false)
D/conversations(26408): reading bitmap with sample size 1
D/conversations(26408): scrolledToBottomAndNoPending=true
D/conversations(26408): jump to first unread message
D/conversations(26408): received uri permission for content://com.android.providers.media.documents/document/image%3A145793
D/conversations(26408): app switched into foreground
D/conversations(26408): ConversationFragment.onBackendConnected()
D/conversations(26408): professor@autistici.org: not counting stanza(IqPacket). Not in smacks session.
D/conversations(26408): professor@autistici.org: starting service discovery
D/conversations(26408): professor@autistici.org: server caps came from cache
D/conversations(26408): professor@autistici.org: stream management(3) enabled (resumable)
D/conversations(26408): professor@autistici.org: Requesting block list
D/conversations(26408): professor@autistici.org: could not query disco info for echo.autistici.org
D/conversations(26408): professor@autistici.org: online with resource Conversations.Pb3x
D/conversations(26408): professor@autistici.org: fetching roster version 8152bed67012e2cbcafeb90f28566e2a017c51a3
D/conversations(26408): professor@autistici.org: running mam query with=*, start=2018-04-25T04:09:21.514Z, end=2018-04-25T04:14:34.325Z, order=NORMAL, catchup=true
D/conversations(26408): professor@autistici.org sending csi//active
D/conversations(26408): AxolotlService (professor@autistici.org): Cache miss: 9f611b4f-1acc-4e08-a6db-e33538d7bef6
D/conversations(26408): AxolotlService (professor@autistici.org): Generated message, caching: 9f611b4f-1acc-4e08-a6db-e33538d7bef6
D/conversations(26408): AxolotlService (professor@autistici.org): Cache hit: 9f611b4f-1acc-4e08-a6db-e33538d7bef6
D/conversations(26408): Received blocklist update from server
D/conversations(26408): professor@autistici.org: successfully enabled carbons
D/conversations(26408): professor@autistici.org: successfully purged offline messages
D/conversations(26408): professor@autistici.org: making disco request for woRXNIgOpKPncctr54UZ7ksSsKM= to benji@wusz.org/gajim.ZZDRBHWEnode=http://gajim.org
D/conversations(26408): send file message
D/conversations(26408): AxolotlService (professor@autistici.org): Bundle 1556427482 in PEP was current
D/conversations(26408): AxolotlService (professor@autistici.org): Announcing device 1556427482
D/conversations(26408): professor@autistici.org: finished mam after 0(0) messages. messages left=true count=0
D/conversations(26408): professor@autistici.org: found 0 pending receipt requests
D/conversations(26408): AxolotlService (professor@autistici.org): Received PEP device list [1500711400, 1556427482] update from professor@autistici.org, processing... 
D/conversations(26408): AxolotlService (professor@autistici.org): Received PEP device list [686490611, 111786015, 1370595158] update from benji@wusz.org, processing... 
D/conversations(26408): AxolotlService (professor@autistici.org): Received PEP device list [686490611, 111786015, 1370595158] update from benji@wusz.org, processing... 
D/conversations(26408): professor@autistici.org: using session Id instead of transport Id for proxy destination
D/conversations(26408): professor@autistici.org: retrieved own device list: [1500711400, 1556427482]
D/conversations(26408): professor@autistici.org: ignoring duplicate own device id list
D/conversations(26408): connection to our own primary candidete failed
D/conversations(26408): professor@autistici.org: mismatch in caps for contact benji@wusz.org/gajim.ZZDRBHWE woRXNIgOpKPncctr54UZ7ksSsKM= vs noD7oYcudxJYUIQyCj1A1A52jYs=
D/conversations(26408): professor@autistici.org: other party received offer
D/conversations(26408): AxolotlService (professor@autistici.org): Finding devices without session for benji@wusz.org
D/conversations(26408): AxolotlService (professor@autistici.org): Cache miss: 6a91e33d-8e0c-431c-aad6-96ae4a8d0860
D/conversations(26408): AxolotlService (professor@autistici.org): Generated message, caching: 6a91e33d-8e0c-431c-aad6-96ae4a8d0860
D/conversations(26408): AxolotlService (professor@autistici.org): Cache hit: 6a91e33d-8e0c-431c-aad6-96ae4a8d0860
```

**Comment by ijneb** [comment]
Closing under the belief that this may have to do more with Gajim's and Pidgin's side.
