### ISSUE TITLE
[BUG] Voice Record failure LineageOS 14.1

### ISSUE THREAD

**Issue by decripter37** [siacs/Conversations#3021]
I had to use a fixed voice recorder for the last version of Conversation, now that it integrates the feature it doesn't work at all and crashes the app.

**Comment by licaon-kter** [comment]
You've installed LineageOS and you ask this? 😉

With a PC via USB, or if you have root use a logcat app like https://github.com/darshanparajuli/LogcatReader or https://github.com/tananaev/rootless-logcat

**Comment by iNPUTmice** [comment]
This is still a bug in Lineage OS. Please report this upstream and provide a link to the report. Also provide more information on what device you are using etc.

**Comment by alexara** [comment]
> This is still a bug in Lineage OS

FYI: LineageOS 14.1-20180421 SerranoLTExx (S4 Mini) is not affected by this bug. The build in voice recorder of Conversations 2.2.0 works fine there.

**Comment by dazzzl** [comment]
I have the same problem. HE_AAC is not working in Lineageos 14.1. Using AAC is fine. I tried to patch Lineageos, however, with no success. 

Is someone here who has Lineageos with a working HE_AAC encoder?
@iNPUTmice: Could you look which encoders are available and switch to AAC as a fall back if HE_AAC is not available?

**Comment by dazzzl** [comment]
@alexara: could you provide the files:

/system/etc/media_codecs.xml
/system/etc/media_profiles.xml

Thanks!

**Comment by iNPUTmice** [comment]
How do I check which Codecs are available though? Also PRs welcome that
only fall back to aac if he_aac is unavailable.

**Comment by alexara** [comment]
@dazzzl 

[media_codecs.xml.txt](https://github.com/siacs/Conversations/files/1987466/media_codecs.xml.txt)
[media_profiles.xml.txt](https://github.com/siacs/Conversations/files/1987467/media_profiles.xml.txt)

It seems that my phone does not support HE_AAC as well, but the internal voice recorder from 2.2.0 works though.

**Comment by dazzzl** [comment]
BTW, this is the complete log:

```
05-09 14:13:57.103   692 12512 I ActivityManager: START u0 {cmp=eu.siacs.conversations/.ui.RecordingActivity} from uid 10080 on display 0
05-09 14:13:57.262   265   399 D audio_hw_primary: adev_open_input_stream: enter: sample_rate(16000) channel_mask(0x10) devices(0x80000004)        stream_handle(0xb56849c0) io_handle(54) source(1)
05-09 14:13:57.267   279  1062 W AudioRecord: Server adjusted notificationFrames from 1024 to 320 for frameCount 2048
05-09 14:13:57.274   279 10868 I MediaPlayerService: MediaPlayerService::getOMX
05-09 14:13:57.275   265 10867 I AudioFlinger: AudioFlinger's thread 0xb41039c0 ready to run
05-09 14:13:57.275   265 10867 D audio_hw_primary: in_standby: enter: stream (0xb56849c0) usecase(7: audio-record)
05-09 14:13:57.277   265 10867 D audio_hw_primary: in_standby: enter: stream (0xb56849c0) usecase(7: audio-record)
05-09 14:13:57.277   279 10868 I OMXClient: MuxOMX ctor
05-09 14:13:57.278   279 10868 I OMXMaster: makeComponentInstance(OMX.qcom.audio.encoder.aac) in mediaserver process
05-09 14:13:57.279   279 10868 E QC_AACENC:  component init: role = OMX.qcom.audio.encoder.aac
05-09 14:13:57.295   279 10868 I MediaCodec: MediaCodec will operate in async mode
05-09 14:13:57.296   279 10868 E OMXNodeInstance: setConfig(1170006:qcom.encoder.aac, ConfigPriority(0x6f800002)) ERROR: UnsupportedIndex(0x8000101a)
05-09 14:13:57.296   279 10868 I ACodec  : codec does not support config priority (err -1010)
05-09 14:13:57.303   279  1062 I MPEG4Writer: limits: 4294967295/0 bytes/us, bit rate: 48000 bps and the estimated moov size 3195 bytes
05-09 14:13:57.304   279 10865 I MediaCodecSource: MediaCodecSource (audio) starting
05-09 14:13:57.307   265 10867 D audio_hw_primary: in_set_parameters: enter: kvpairs=input_source=1;routing=-2147483644
05-09 14:13:57.308   265 10867 D audio_hw_primary: start_input_stream: enter: stream(0xb56849c0)usecase(7: audio-record)
05-09 14:13:57.308   265 10867 D audio_hw_primary: select_devices: out_snd_device(0: ) in_snd_device(31: handset-mic)
05-09 14:13:57.308   265 10867 I msm8960_platform: platform_send_audio_calibration: sending audio calibration for snd_device(31) acdb_id(4)
05-09 14:13:57.309   265 10867 D ACDB-LOADER: ACDB -> send_audio_cal, acdb_id = 4, path =  1
05-09 14:13:57.309   265 10867 D ACDB-LOADER: ACDB -> send_adm_topology
05-09 14:13:57.309   265 10867 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TOPOLOGY_ID
05-09 14:13:57.309   265 10867 D ACDB-LOADER: ACDB -> send_audtable
05-09 14:13:57.309   265 10867 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TABLE
05-09 14:13:57.309   265 10867 D ACDB-LOADER: ACDB -> AUDIO_SET_AUDPROC_CAL
05-09 14:13:57.309   265 10867 D ACDB-LOADER: ACDB -> send_audvoltable
05-09 14:13:57.309   265 10867 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_GAIN_DEP_VOLTBL_STEP_COPP
05-09 14:13:57.309   265 10867 E ACDB-LOADER: Error: ACDB AudProc vol returned = -8
05-09 14:13:57.309   265 10867 D ACDB-LOADER: ACDB -> AUDIO_SET_AUDPROC_VOL_CAL
05-09 14:13:57.309   265 10867 D ACDB-LOADER: ACDB -> AUDIO_SET_AFE_CAL
05-09 14:13:57.312   279 10865 I MediaCodecSource: MediaCodecSource (audio) started
05-09 14:13:57.315 10745 10745 D Voice Recorder: started recording to /storage/emulated/0/Conversations/Media/Conversations Recordings/RECORDING_20180509_141357228.m4a
05-09 14:13:57.319   265 10867 D audio_hw_primary: select_devices: done
05-09 14:13:57.319   279 10870 E QC_AACENC: ioctl AUDIO_SET_AAC_CONFIG failed,                                  errno[22]
05-09 14:13:57.465   692   729 I ActivityManager: Displayed eu.siacs.conversations/.ui.RecordingActivity: +332ms
05-09 14:13:57.559 10745 10745 D conversations: ignoring read callback. mActivityPaused=true
05-09 14:13:57.559 10745 10745 W IInputConnectionWrapper: finishComposingText on inactive InputConnection
05-09 14:13:59.937   279  1073 D MPEG4Writer: Audio track stopping
05-09 14:13:59.937   279  1073 D MPEG4Writer: Audio track source stopping
05-09 14:13:59.937   279 10865 I MediaCodecSource: encoder (audio) stopping
05-09 14:13:59.948   279 10875 E MPEG4Writer: The number of recorded samples is 0
05-09 14:13:59.948   279 10875 W MPEG4Writer: 0-duration samples found: 1
05-09 14:13:59.948   279 10875 W MPEG4Writer: 0-duration samples found: 1
05-09 14:13:59.948   279 10875 I MPEG4Writer: Received total/0-length (1/0) buffers and encoded 0 frames. - Audio
05-09 14:13:59.951   279 10875 I MPEG4Writer: Audio track drift time: 0 us
05-09 14:13:59.967   279 10868 E QC_AACENC: component_deinit:COMPONENT DEINIT...
05-09 14:13:59.967   279 10868 E QC_AACENC: AAC Object getting destroyed comp-deinit=1
05-09 14:13:59.967   279 10868 E QC_AACENC: OMX AAC component destroyed
05-09 14:13:59.970   279 10865 I MediaCodecSource: encoder (audio) stopped
05-09 14:13:59.980   265 10867 D audio_hw_primary: in_standby: enter: stream (0xb56849c0) usecase(7: audio-record)
05-09 14:14:00.031   265 10867 D audio_hw_primary: in_set_parameters: enter: kvpairs=routing=0
05-09 14:14:00.034   279  1073 D MPEG4Writer: Audio track source stopped
05-09 14:14:00.034   279  1073 D MPEG4Writer: Audio track stopped
05-09 14:14:00.034   279  1073 D MPEG4Writer: Stopping writer thread
05-09 14:14:00.034   279 10873 D MPEG4Writer: 0 chunks are written in the last batch
05-09 14:14:00.035   279  1073 D MPEG4Writer: Writer thread stopped
05-09 14:14:00.035   279  1073 D MPEG4Writer: Audio track stopping
05-09 14:14:00.040 10745 10745 E MediaRecorder: stop failed: -1007
05-09 14:14:00.063 10745 10745 D AndroidRuntime: Shutting down VM
05-09 14:14:00.074 10745 10745 E AndroidRuntime: FATAL EXCEPTION: main
05-09 14:14:00.074 10745 10745 E AndroidRuntime: Process: eu.siacs.conversations, PID: 10745
05-09 14:14:00.074 10745 10745 E AndroidRuntime: java.lang.RuntimeException: stop failed.
05-09 14:14:00.074 10745 10745 E AndroidRuntime:        at android.media.MediaRecorder.stop(Native Method)
05-09 14:14:00.074 10745 10745 E AndroidRuntime:        at eu.siacs.conversations.ui.RecordingActivity.stopRecording(RecordingActivity.java:111)
05-09 14:14:00.074 10745 10745 E AndroidRuntime:        at eu.siacs.conversations.ui.RecordingActivity.lambda$onClick$0$RecordingActivity(RecordingActivity.java:184)
05-09 14:14:00.074 10745 10745 E AndroidRuntime:        at eu.siacs.conversations.ui.RecordingActivity$$Lambda$0.run(Unknown Source)
05-09 14:14:00.074 10745 10745 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:751)
05-09 14:14:00.074 10745 10745 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
05-09 14:14:00.074 10745 10745 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
05-09 14:14:00.074 10745 10745 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6186)
05-09 14:14:00.074 10745 10745 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
05-09 14:14:00.074 10745 10745 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
05-09 14:14:00.074 10745 10745 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
05-09 14:14:00.084   692 14079 W ActivityManager:   Force finishing activity eu.siacs.conversations/.ui.ConversationsActivity
```

**Comment by licaon-kter** [comment]
@dazzzl Please use https://gist.github.com to paste the log and edit your post only with the link.

**Comment by alexara** [comment]
@dazzzl 

> Thanks, but I have almost the same files. Could you look into the media_codes*.xml files if you find some aac or heaac encoders? I have only the google aac encoder.

```
adb shell grep -iRn --include="media_codecs_*.xml" "aac" /system/etc/
/system/etc/media_codecs_ffmpeg.xml:21:        <MediaCodec name="OMX.ffmpeg.aac.decoder"    type="audio/mp4a-latm">
/system/etc/media_codecs_google_audio.xml:34:        <MediaCodec name="OMX.google.aac.decoder" type="audio/mp4a-latm">
/system/etc/media_codecs_google_audio.xml:66:        <MediaCodec name="OMX.google.aac.encoder" type="audio/mp4a-latm">
```

A search for `heacc` yielded no result.
