### ISSUE TITLE
TLS error with Openfire

### ISSUE THREAD

**Issue by ateymoori** [siacs/Conversations#3078]
Hi
I am using conversation + Openfire (installed on ubuntu 16.04) 
with no ssl certificate
address: alborzhosting.com

in connecting app to server, i received bottom error.
but i can use spark to connect with no problem
how to resolve?

#### General information

* **Version:** eg 1.21.0
* **Device:** eg Google Nexus 5x
* **Android Version:** eg Android 8.0 
* **Server name:** Openfire

adb logcat -s conversations

`06-14 18:44:13.716 604-649/eu.siacs.conversations W/System.err: javax.net.ssl.SSLPeerUnverifiedException: No peer certificates
06-14 18:44:13.717 604-649/eu.siacs.conversations W/System.err:     at com.android.org.conscrypt.SessionSnapshot.getPeerCertificates(SessionSnapshot.java:133)
        at com.android.org.conscrypt.ExternalSession.getPeerCertificates(ExternalSession.java:111)
        at com.android.org.conscrypt.Java7ExtendedSSLSession.getPeerCertificates(Java7ExtendedSSLSession.java:133)
        at com.android.org.conscrypt.Java7ExtendedSSLSession.getPeerCertificates(Java7ExtendedSSLSession.java:30)
        at eu.siacs.conversations.services.MemorizingTrustManager$MemorizingHostnameVerifier.verify(MemorizingTrustManager.java:808)
        at eu.siacs.conversations.xmpp.XmppConnection.switchOverToTls(XmppConnection.java:826)
        at eu.siacs.conversations.xmpp.XmppConnection.processStream(XmppConnection.java:496)
        at eu.siacs.conversations.xmpp.XmppConnection.connect(XmppConnection.java:410)
        at eu.siacs.conversations.xmpp.XmppConnection.run(XmppConnection.java:483)
        at java.lang.Thread.run(Thread.java:764)
06-14 18:44:13.718 604-649/eu.siacs.conversations D/conversations: ali@alborzhosting.com: TLS certificate verification failed
06-14 18:44:13.719 604-649/eu.siacs.conversations D/conversations: ali@alborzhosting.com: error connecting account. try again in 24s for the 1 time. lowPingTimeout=false`

````

**Comment by licaon-kter** [comment]
You can't connect without TLS, do get a free Let's Encrypt certificate, c'mon! 🤘

**Comment by ateymoori** [comment]
do you know any simple tutorial ? (lets encrypt and openfire)

**Comment by licaon-kter** [comment]
No, http://download.igniterealtime.org/openfire/docs/latest/documentation/ssl-guide.html ?
