### ISSUE TITLE
Crash: Cropping / Publishing (Group) Avatar

### ISSUE THREAD

**Issue by tyler71** [siacs/Conversations#3136]
#### General information

* **Version:** 2.2.8+pcr
* **Device:** Samsung Galaxy J3
* **Android Version:** Android 7.0 Stock
* **Server name:** self
* **Server software:** prosody trunk
* **Installed server modules:** adhoc admin_adhoc auth_internal_hashed blocklist c2s carbons cloud_notify csi csi_battery_saver disco groups http_upload_external iq lastactivity mam mam_archive message offline omemo_all_access pep pep_plus ping presence private profile proxy65 register roster s2s s2s_whitelist saslauth server_contact_info smacks smacks_offline storage_internal storage_sql time tls track_muc_joins uptime user_account_management version
* **Conversations source:** PlayStore Beta Channel
#### Steps to reproduce

1. Go to Group chat avatar
2. Select new image
3. crop
4. Hit publish

#### Expected result
Publish avatar to group chat 

#### Actual result
OOM error
```
Version: 2.2.8+pcr
Last Update: 2018-07-23
SHA-1: 6f:80:8b:e7:c4:81:e6:f0:16:f7:19:ba:9d:6e:d7:af:c3:1c:44:5e

java.lang.OutOfMemoryError: Failed to allocate a 27836776 byte allocation with 4013784 free bytes and 3MB until OOM
	at java.lang.StringFactory.newStringFromChars(StringFactory.java:218)
	at java.lang.StringFactory.newStringFromBytes(StringFactory.java:203)
	at java.lang.StringFactory.newStringFromBytes(StringFactory.java:53)
	at java.lang.StringFactory.newStringFromBytes(StringFactory.java:45)
	at eu.siacs.conversations.persistance.FileBackend.getPepAvatar(FileBackend.java:814)
	at eu.siacs.conversations.persistance.FileBackend.getUncompressedAvatar(FileBackend.java:785)
	at eu.siacs.conversations.persistance.FileBackend.getPepAvatar(FileBackend.java:760)
	at eu.siacs.conversations.services.XmppConnectionService.lambda$publishMucAvatar$23$XmppConnectionService(XmppConnectionService.java:2754)
	at eu.siacs.conversations.services.XmppConnectionService$$Lambda$25.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:762)

``` 

#### Debug output

Please post the output of adb logcat. The log should begin with the start of Conversations and include all the
steps it takes to reproduce the problem.

````
08-02 09:31:59.063   569   569 D conversations: app switched into background    
08-02 09:32:23.606   569   569 D conversations: loading file:///data/user/0/eu.siacs.conversations/cache/cropped1040539101.png into preview
08-02 09:32:42.678   569   698 D conversations: settled on char length 14501102 with quality=100
08-02 09:32:43.775   569   569 D conversations: nulluser@null.null send ping (action=ui,lowTimeout=false)
08-02 09:32:43.824   569   569 D conversations: app switched into foreground
````
I went through a unfiltered logcat too, I believe this is relevant

```
08-02 09:07:38.824 12069 31731 D conversations: settled on char length 13918378 with quality=100
08-02 09:07:38.843 12069 31731 I art     : Starting a blocking GC Alloc         
08-02 09:07:38.843 12069 31731 I art     : Starting a blocking GC Alloc         
08-02 09:07:38.852 12069 31731 I art     : Alloc sticky concurrent mark sweep GC freed 327(24KB) AllocSpace objects, 0(0B) LOS objects, 3% free, 87MB/90MB, paused 873us total 8.775ms
08-02 09:07:38.852 12069 31731 I art     : Starting a blocking GC Alloc         
08-02 09:07:38.907 12069 31731 I art     : Alloc partial concurrent mark sweep GC freed 33(16KB) AllocSpace objects, 1(21MB) LOS objects, 19% free, 65MB/81MB, paused 913us total 54.769ms
08-02 09:07:38.967 12069 12079 I art     : Clamp target GC heap from 108MB to 96MB
08-02 09:07:39.240 12069 31731 I art     : Starting a blocking GC Alloc         
08-02 09:07:39.241 12069 31731 I art     : Starting a blocking GC Alloc         
08-02 09:07:39.249 12069 31731 I art     : Alloc sticky concurrent mark sweep GC freed 0(0B) AllocSpace objects, 0(0B) LOS objects, 3% free, 92MB/96MB, paused 910us total 7.857ms
08-02 09:07:39.249 12069 31731 I art     : Starting a blocking GC Alloc         
08-02 09:07:39.303 12069 31731 I art     : Clamp target GC heap from 108MB to 96MB
08-02 09:07:39.303 12069 31731 I art     : Alloc partial concurrent mark sweep GC freed 6(144B) AllocSpace objects, 0(0B) LOS objects, 3% free, 92MB/96MB, paused 1.114ms total 53.934ms
08-02 09:07:39.303 12069 31731 I art     : Starting a blocking GC Alloc         
08-02 09:07:39.387 12069 31731 I art     : Clamp target GC heap from 108MB to 96MB
08-02 09:07:39.387 12069 31731 I art     : Alloc concurrent mark sweep GC freed 17(592B) AllocSpace objects, 0(0B) LOS objects, 3% free, 92MB/96MB, paused 995us total 84.125ms
08-02 09:07:39.387 12069 31731 I art     : Forcing collection of SoftReferences for 26MB allocation
08-02 09:07:39.387 12069 31731 I art     : Starting a blocking GC Alloc         
08-02 09:07:39.470 12069 31731 I art     : Clamp target GC heap from 108MB to 96MB
08-02 09:07:39.470 12069 31731 I art     : Alloc concurrent mark sweep GC freed 3(72B) AllocSpace objects, 0(0B) LOS objects, 3% free, 92MB/96MB, paused 852us total 82.426ms
08-02 09:07:39.470 12069 31731 W art     : Throwing OutOfMemoryError "Failed to allocate a 27836776 byte allocation with 4013560 free bytes and 3MB until OOM"
08-02 09:07:39.472 12069 31731 I art     : Starting a blocking GC Alloc         
08-02 09:07:39.472 12069 31731 I art     : Starting a blocking GC Alloc         
08-02 09:07:39.480 12069 31731 I art     : Alloc sticky concurrent mark sweep GC freed 4(376B) AllocSpace objects, 0(0B) LOS objects, 3% free, 92MB/96MB, paused 802us total 7.438ms
08-02 09:07:39.480 12069 31731 I art     : Starting a blocking GC Alloc         
08-02 09:07:39.531 12069 31731 I art     : Clamp target GC heap from 108MB to 96MB
08-02 09:07:39.531 12069 31731 I art     : Alloc partial concurrent mark sweep GC freed 6(144B) AllocSpace objects, 0(0B) LOS objects, 3% free, 92MB/96MB, paused 882us total 50.876ms
08-02 09:07:39.531 12069 31731 I art     : Starting a blocking GC Alloc         
08-02 09:07:39.613 12069 31731 I art     : Clamp target GC heap from 108MB to 96MB
08-02 09:07:39.613 12069 31731 I art     : Alloc concurrent mark sweep GC freed 3(72B) AllocSpace objects, 0(0B) LOS objects, 3% free, 92MB/96MB, paused 862us total 82.049ms
08-02 09:07:39.613 12069 31731 I art     : Forcing collection of SoftReferences for 26MB allocation
08-02 09:07:39.613 12069 31731 I art     : Starting a blocking GC Alloc         
08-02 09:07:39.696 12069 31731 I art     : Clamp target GC heap from 108MB to 96MB
08-02 09:07:39.696 12069 31731 I art     : Alloc concurrent mark sweep GC freed 3(72B) AllocSpace objects, 0(0B) LOS objects, 3% free, 92MB/96MB, paused 874us total 82.549ms
08-02 09:07:39.696 12069 31731 I art     : Starting a blocking GC HomogeneousSpaceCompact
08-02 09:07:39.796 12069 31731 I art     : Clamp target GC heap from 108MB to 96MB
08-02 09:07:39.796 12069 31731 I art     : HomogeneousSpaceCompact marksweep + semispace GC freed 0(0B) AllocSpace objects, 0(0B) LOS objects, 3% free, 92MB/96MB, paused 99.314ms total 99.314ms
08-02 09:07:39.796 12069 31731 W art     : Throwing OutOfMemoryError "Failed to allocate a 27836776 byte allocation with 4013784 free bytes and 3MB until OOM"
--------- beginning of crash                                                    
08-02 09:07:39.799 12069 31731 E AndroidRuntime: FATAL EXCEPTION: Thread-24     
08-02 09:07:39.799 12069 31731 E AndroidRuntime: Process: eu.siacs.conversations, PID: 12069
08-02 09:07:39.799 12069 31731 E AndroidRuntime: java.lang.OutOfMemoryError: Failed to allocate a 27836776 byte allocation with 4013784 free bytes and 3MB until OOM
08-02 09:07:39.799 12069 31731 E AndroidRuntime:    at java.lang.StringFactory.newStringFromChars(StringFactory.java:218)
08-02 09:07:39.799 12069 31731 E AndroidRuntime:    at java.lang.StringFactory.newStringFromBytes(StringFactory.java:203)
08-02 09:07:39.799 12069 31731 E AndroidRuntime:    at java.lang.StringFactory.newStringFromBytes(StringFactory.java:53)
08-02 09:07:39.799 12069 31731 E AndroidRuntime:    at java.lang.StringFactory.newStringFromBytes(StringFactory.java:45)
08-02 09:07:39.799 12069 31731 E AndroidRuntime:    at eu.siacs.conversations.persistance.FileBackend.getPepAvatar(FileBackend.java:814)
08-02 09:07:39.799 12069 31731 E AndroidRuntime:    at eu.siacs.conversations.persistance.FileBackend.getUncompressedAvatar(FileBackend.java:785)
08-02 09:07:39.799 12069 31731 E AndroidRuntime:    at eu.siacs.conversations.persistance.FileBackend.getPepAvatar(FileBackend.java:760)
08-02 09:07:39.799 12069 31731 E AndroidRuntime:    at eu.siacs.conversations.services.XmppConnectionService.lambda$publishMucAvatar$23$XmppConnectionService(XmppConnectionService.java:2754)
08-02 09:07:39.799 12069 31731 E AndroidRuntime:    at eu.siacs.conversations.services.XmppConnectionService$$Lambda$25.run(Unknown Source)
08-02 09:07:39.799 12069 31731 E AndroidRuntime:    at java.lang.Thread.run(Thread.java:762)
```

**Comment by licaon-kter** [comment]
A smaller image works?

**Comment by tyler71** [comment]
Yeah, a smaller image works (200kb)
Mine was 3.6MB. 

[profile](https://modules.prosody.im/mod_profile.html) apparently replaces some parts of vcard

So I cropped the image to be even smaller and it published

**Comment by licaon-kter** [comment]
Looks like the cropper failed, eg. Your 3.6Mb image ended up as a 14Mb PNG file....hence...

So maybe rename the issue

**Comment by licaon-kter** [comment]
@tyler71 FYI https://blog.prosody.im/pep-improvements-in-trunk/

**Comment by iNPUTmice** [comment]
should work in master

**Comment by tyler71** [comment]
Could no longer trigger with recent update
