### ISSUE TITLE
HTTP upload/download failing

### ISSUE THREAD

**Issue by apprb** [siacs/Conversations#3251]
#### General information

* **Version:** 2.3.4+fcr
* **Device:** Xiaomi 3S
* **Android Version:** LineageOS 15.1
* **Server name:** draugr.de
* **Server software:** ejabberd 18.09 
* **Conversations source:** F-Droid

#### Steps to reproduce

1a. Send an image to another contact/group chat
1b. Try to get an image from draugr.de server

#### Expected result

Image should be sent/received.

#### Actual result

Downloading/sending failing.

##### Sending log:
````
10-25 23:09:47.090  4555  4555 D conversations: XXXX@draugr.de: not compressing picture. sending as file
10-25 23:09:47.108  4555  4555 D conversations: received uri permission for content://com.android.providers.media.documents/document/image%3A2942
10-25 23:09:47.124  4555  6686 D conversations: send file message
10-25 23:09:47.270  2373  3870 I NotificationService: cancelToast pkg=eu.siacs.conversations callback=android.app.ITransientNotification$Stub$Proxy@b57a6bd
10-25 23:09:47.275  2373  3870 W WindowManager: removeWindowToken: Attempted to remove non-existing token: android.os.Binder@f40fc05
10-25 23:09:47.313  4555  7601 D conversations: uploading to https://draugr.de:5443/upload/4c06010f4ea5aedd96b37ed3836701d031e699d4/Lr6Td9J9Gr6lCM1SRPkCYBwu0ESAfbmOsBUopDMa/IMG-20181025-WA0009.jpg w/ read timeout of 71s
10-25 23:09:47.808  4555  7601 W System.err: java.io.IOException: unexpected end of stream on com.android.okhttp.Address@e56a8c05
10-25 23:09:47.808  4555  7601 W System.err: 	at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:201)
10-25 23:09:47.808  4555  7601 W System.err: 	at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
10-25 23:09:47.808  4555  7601 W System.err: 	at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737)
10-25 23:09:47.808  4555  7601 W System.err: 	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:609)
10-25 23:09:47.808  4555  7601 W System.err: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:471)
10-25 23:09:47.808  4555  7601 W System.err: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
10-25 23:09:47.808  4555  7601 W System.err: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:538)
10-25 23:09:47.809  4555  7601 W System.err: 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
10-25 23:09:47.809  4555  7601 W System.err: 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(Unknown Source:0)
10-25 23:09:47.809  4555  7601 W System.err: 	at eu.siacs.conversations.http.HttpUploadConnection.upload(HttpUploadConnection.java:192)
10-25 23:09:47.809  4555  7601 W System.err: 	at eu.siacs.conversations.http.HttpUploadConnection.access$300(HttpUploadConnection.java:30)
10-25 23:09:47.809  4555  7601 W System.err: 	at eu.siacs.conversations.http.HttpUploadConnection$1.lambda$success$0(HttpUploadConnection.java:134)
10-25 23:09:47.809  4555  7601 W System.err: 	at eu.siacs.conversations.http.-$$Lambda$HttpUploadConnection$1$xe9LFzy6COS1JMdivVN6RPSpYq4.run(Unknown Source:2)
10-25 23:09:47.809  4555  7601 W System.err: 	at java.lang.Thread.run(Thread.java:764)
10-25 23:09:47.809  4555  7601 W System.err: Caused by: java.io.EOFException: \n not found: size=0 content=...
10-25 23:09:47.809  4555  7601 W System.err: 	at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:200)
10-25 23:09:47.809  4555  7601 W System.err: 	at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
10-25 23:09:47.809  4555  7601 W System.err: 	... 13 more
10-25 23:09:47.809  4555  7601 D conversations: http upload failed unexpected end of stream on com.android.okhttp.Address@e56a8c05
````
##### Receiving log:
````
10-25 23:07:52.508  4555  7544 D conversations: retrieve file size. interactive:true
10-25 23:07:52.510  4555  7544 D conversations: url: https://draugr.de:5443/upload/73125f60df404871e5554d294c532fb05c1b0e5d/02JHG6wUCJZw1r4EPIQcsLZaQ7T6MFubb4zmMEzJ/ktG8m6sTTPC53UNGIBkeqg.png
10-25 23:07:52.996  4555  7544 D conversations: io exception during HEAD no content-length found in HEAD response
10-25 23:07:52.996  4555  7544 D conversations: io exception in http file size checker: no content-length found in HEAD response
````

I believe that this actually not two separated issues but one.

Using the same account with the same Conversations version but on another device with LineageOS 14.1 gives no errors.

**Comment by iNPUTmice** [comment]
It seems to me like the IPv6 address of the host isn’t available.

**Comment by apprb** [comment]
For mobile network there's no IPv6. So even there's wrong AAAA record in DNS it shouldn't affect IPv4 only connection.

**Comment by licaon-kter** [comment]
@apprb Using any proxy/VPN?

**Comment by apprb** [comment]
Initially used no VPN/proxy. But with VPN the issue is still observable.
If you have any ideas about what to check I can provide additional logs or information about it.

**Comment by licaon-kter** [comment]
Seeing the same too BTW.

**Comment by iNPUTmice** [comment]
@apprb seems like a server issue to me

@licaon-kter on that particular server? Or with the same ejabberd version?

**Comment by licaon-kter** [comment]
@iNPUTmice that server
