### ISSUE TITLE
XmppConnectionService: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.contacts.ContactsProvider2  Android 8.1.0 (Redmi note 5 pro)

### ISSUE THREAD

**Issue by bhoomesh950** [siacs/Conversations#3267]
java.lang.RuntimeException: Unable to create service com.ticktok.services.XmppConnectionService: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.contacts.ContactsProvider2 from ProcessRecord{b1c2482 3242:com.ticktok/u0a300} (pid=3242, uid=10300) requires android.permission.READ_CONTACTS or android.permission.WRITE_CONTACTS
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3383)
        at android.app.ActivityThread.-wrap4(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1701)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:171)
        at android.app.ActivityThread.main(ActivityThread.java:6633)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
     Caused by: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.contacts.ContactsProvider2 from ProcessRecord{b1c2482 3242:com.ticktok/u0a300} (pid=3242, uid=10300) requires android.permission.READ_CONTACTS or android.permission.WRITE_CONTACTS
        at android.os.Parcel.readException(Parcel.java:2005)
        at android.os.Parcel.readException(Parcel.java:1951)
        at android.content.IContentService$Stub$Proxy.registerContentObserver(IContentService.java:768)
        at android.content.ContentResolver.registerContentObserver(ContentResolver.java:1940)
        at android.content.ContentResolver.registerContentObserver(ContentResolver.java:1929)
        at com.ticktok.services.XmppConnectionService.onCreate(XmppConnectionService.java:1021)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3373)
        at android.app.ActivityThread.-wrap4(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1701) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:171) 
        at android.app.ActivityThread.main(ActivityThread.java:6633) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823) 

The above issue occurring only Android Version 8.1.0 (RedMi note 5 pro) please help me how can i resolve the issue ?

**Comment by licaon-kter** [comment]
So you've denied contacts access? Conversations 2.3.5 right?
