### ISSUE TITLE
Changing MUC Nickname -> "Conversations has stopped"

### ISSUE THREAD

**Issue by streaps** [siacs/Conversations#3279]
#### General information

* **Version:** 2.3.6+pcd
* **Device:** Samsung Galaxy S3 
* **Android Version:** Android 7.1.2 LineageOS
* **Conversations source:** self build 

#### Steps to reproduce
1. Change Nickname in MUC

#### Actual result
Nickname is changed
Error: "Conversations has stopped"

#### Debug output
```
11-17 10:21:41.134  3182  3182 E AndroidRuntime: FATAL EXCEPTION: main
11-17 10:21:41.134  3182  3182 E AndroidRuntime: Process: eu.siacs.conversations, PID: 3182
11-17 10:21:41.134  3182  3182 E AndroidRuntime: android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@8ab4251 is not valid; is your activity running?
11-17 10:21:41.134  3182  3182 E AndroidRuntime:        at android.view.ViewRootImpl.setView(ViewRootImpl.java:679)
11-17 10:21:41.134  3182  3182 E AndroidRuntime:        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:342)
11-17 10:21:41.134  3182  3182 E AndroidRuntime:        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
11-17 10:21:41.134  3182  3182 E AndroidRuntime:        at android.widget.Toast$TN.handleShow(Toast.java:459)
11-17 10:21:41.134  3182  3182 E AndroidRuntime:        at android.widget.Toast$TN$2.handleMessage(Toast.java:342)
11-17 10:21:41.134  3182  3182 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
11-17 10:21:41.134  3182  3182 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
11-17 10:21:41.134  3182  3182 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6186)
11-17 10:21:41.134  3182  3182 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
11-17 10:21:41.134  3182  3182 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
11-17 10:21:41.134  3182  3182 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

```

**Comment by licaon-kter** [comment]
Can you repro this with the F-Droid version?

**Comment by streaps** [comment]
It still exits with the same exception.

**Comment by iNPUTmice** [comment]
@streaps please post the stack trace again. it at least show have a different line

**Comment by streaps** [comment]
```
11-18 15:19:55.437 29643 29643 E AndroidRuntime: FATAL EXCEPTION: main
11-18 15:19:55.437 29643 29643 E AndroidRuntime: Process: eu.siacs.conversations, PID: 29643
11-18 15:19:55.437 29643 29643 E AndroidRuntime: android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@6355fe3 is not valid; is your activity running?
11-18 15:19:55.437 29643 29643 E AndroidRuntime:        at android.view.ViewRootImpl.setView(ViewRootImpl.java:679)
11-18 15:19:55.437 29643 29643 E AndroidRuntime:        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:342)
11-18 15:19:55.437 29643 29643 E AndroidRuntime:        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
11-18 15:19:55.437 29643 29643 E AndroidRuntime:        at android.widget.Toast$TN.handleShow(Toast.java:459)
11-18 15:19:55.437 29643 29643 E AndroidRuntime:        at android.widget.Toast$TN$2.handleMessage(Toast.java:342)
11-18 15:19:55.437 29643 29643 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
11-18 15:19:55.437 29643 29643 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
11-18 15:19:55.437 29643 29643 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6186)
11-18 15:19:55.437 29643 29643 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
11-18 15:19:55.437 29643 29643 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
11-18 15:19:55.437 29643 29643 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by iNPUTmice** [comment]
does current master fix the issue? apparently it only happens on Android 7.1

**Comment by streaps** [comment]
nope, still the same stack trace.

There's some small difference, though. The nickname changes (visually) before Conversations exits. In a previous version I couldn't see the nicḱname changing.

**Comment by iNPUTmice** [comment]
Does the latest head fix the issue for you?

**Comment by streaps** [comment]
it does fix the issue :)
