### ISSUE TITLE
Application crashes in "Add account" when Jabber ID field loses focus

### ISSUE THREAD

**Issue by wymiatacz** [siacs/Conversations#3283]
#### General information

* **Version:** 2.3.6
* **Device:** Meizu Pro 6
* **Android Version:** Android 7.1.1
* **Conversations source:** self build (latest HEAD)

#### Steps to reproduce

1. Launch Conversations -> "Join the Conversation" appears
2. Select "USE MY OWN PROVIDER" -> "Add account" appears
3. Type something under "Jabber ID" or leave the field blank
4. Tap on "Password"

#### Expected result

"Password" field is focused

#### Actual result

Application crashes

#### Debug output

````
13964 13964 E AndroidRuntime: FATAL EXCEPTION: main
13964 13964 E AndroidRuntime: Process: eu.siacs.conversations, PID: 13964
13964 13964 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.text.Layout.getLineForOffset(int)' on a null object reference
13964 13964 E AndroidRuntime: 	at android.widget.Editor.updateCursorPositionMz(Editor.java:7878)
13964 13964 E AndroidRuntime: 	at android.widget.Editor.updateCursorsPositions(Editor.java:1968)
13964 13964 E AndroidRuntime: 	at android.widget.TextView.getUpdatedHighlightPath(TextView.java:5891)
13964 13964 E AndroidRuntime: 	at android.widget.TextView.onDraw(TextView.java:6083)
13964 13964 E AndroidRuntime: 	at android.view.View.draw(View.java:17566)
13964 13964 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:16501)
13964 13964 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3844)
13964 13964 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3824)
13964 13964 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:16455)
13964 13964 E AndroidRuntime: 	at android.view.View.draw(View.java:17312)
13964 13964 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:3860)
13964 13964 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3646)
13964 13964 E AndroidRuntime: 	at android.view.View.draw(View.java:17578)
13964 13964 E AndroidRuntime: 	at android.support.design.widget.TextInputLayout.draw(TextInputLayout.java:1577)
13964 13964 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:16501)
13964 13964 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3844)
13964 13964 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3824)
13964 13964 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:16455)
13964 13964 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3844)
13964 13964 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3824)
13964 13964 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:16455)
13964 13964 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3844)
13964 13964 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3824)
13964 13964 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:16455)
13964 13964 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3844)
13964 13964 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3824)
13964 13964 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:16455)
13964 13964 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3844)
13964 13964 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3824)
13964 13964 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:16455)
13964 13964 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3844)
13964 13964 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3824)
13964 13964 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:16455)
13964 13964 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3844)
13964 13964 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3824)
13964 13964 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:16455)
13964 13964 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3844)
13964 13964 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3824)
13964 13964 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:16455)
13964 13964 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3844)
13964 13964 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3824)
13964 13964 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:16455)
13964 13964 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3844)
13964 13964 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3824)
13964 13964 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:16455)
13964 13964 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3844)
13964 13964 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3824)
13964 13964 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:16455)
13964 13964 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:666)
13964 13964 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:672)
13964 13964 E AndroidRuntime: 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:780)
13964 13964 E AndroidRuntime: 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3232)
13964 13964 E AndroidRuntime: 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3019)
13964 13964 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2601)
13964 13964 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1494)
13964 13964 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7145)
13964 13964 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:924)
13964 13964 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:726)
13964 13964 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:660)
13964 13964 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:910)
13964 13964 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:836)
13964 13964 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:103)
13964 13964 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:203)
13964 13964 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6564)
13964 13964 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
13964 13964 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1134)
13964 13964 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
  962  2430 I ActivityManager: addErrorToDropBox eu.siacs.conversations crash
 1345  1345 I MzInput_MzInputService: theme= white mNeedBlur=false
  962  2430 I ActivityManager: process is not media, so return default packageNameeu.siacs.conversations
  962  2430 I ActivityManager: addErrorToDropbox, real report package is eu.siacs.conversations
  962  2430 W ActivityManager:   Force finishing activity eu.siacs.conversations/.ui.EditAccountActivity
  962  1332 I libPerfService: 1: set freq: 1547000, 2002000, 2522000, 
  962  1332 I libPerfService: 1: set: -1, 4, -1, 
  962  2430 W ActivityManager:   Force finishing activity eu.siacs.conversations/.ui.EditAccountActivity
  962  2430 W ActivityManager:   Force finishing activity eu.siacs.conversations/.ui.WelcomeActivity
  962  1332 I libPerfService: 2: set: -1, 4, 2, 
  962  1332 I libPerfService: [perfNotifyAppState] foreground:com.meizu.flyme.launcher, pid:2427
  962  1332 I libPerfService: [switchSportsMode] enable:0, currPower:0
  962  2430 E ActivityManager: Found activity ActivityRecord{b121f50 u0 eu.siacs.conversations/.ui.WelcomeActivity t234 f} in proc activity list using null instead of expected ProcessRecord{8d153d9 13964:eu.siacs.conversations/u0a130}
  962  2430 I ActivityManager: Killing 13964:eu.siacs.conversations/u0a130 (adj 0): crash

````

**Comment by licaon-kter** [comment]
If you can't repro this with the F-Droid build... this is not a support site for forks.

**Comment by wymiatacz** [comment]
A fork? No, I checked out and built the code of this particular repo.
676d31f60607656b064e8ada59f314bca75a3c48 is the commit which introduced this problem.

**Comment by licaon-kter** [comment]
Again, can you repro with the F-Droid APK?

**Comment by iNPUTmice** [comment]
Looks very much like a fuckup in your ROM. Have fun debugging this.

**Comment by iNPUTmice** [comment]
https://stackoverflow.com/questions/51891415/nullpointerexception-on-meizu-devices-in-editor-updatecursorpositionmz

and that chinese thread with what seems to be a solution in the last post https://github.com/android-in-china/Compatibility/issues/11

If you try that on your device and make a PR I’ll merge it.

**Comment by wymiatacz** [comment]
Thanks for quick and helpful response. Removing hints from the XML indeed helped. (I haven't prepared a fully working patch yet, though.)

**Comment by iNPUTmice** [comment]
@wymiatacz can you check out the latest HEAD? It should have a fix for that.

**Comment by wymiatacz** [comment]
It works, thanks!
