### ISSUE TITLE
Crash of app 5 to 10 seconds after startup

### ISSUE THREAD

**Issue by mistersixt** [siacs/Conversations#3345]
#### General information

* **Version:** 2.3.11+pcr
* **Device:** HTC 10
* **Android Version:** Android 7.1.2, LineageOS 14
* **Server name:** www.jabber-germany.de
* **Server software:** prosody 0.11.2
* **Installed server modules:** XEP-0198, smacks_offline, XEP-0280, XEP-0065, XEP-0012, XEP-0092, XEP-0030, XEP-0163, XEP-0199, XEP-0090, XEP-0202, XEP-0054, XEP-0237, XEP-0357, XEP-0191, XEP-0124, XEP-0206, XEP-0352, XEP-0363, XEP-0313, mod_muc_mam, mod_vcard4, mod_vcard_legacy, XEP-0384, csi_battery_saver
* **Conversations source:** PlayStore

Hi Daniel,

since yesterday morning my Conversations keeps crashing on my HTC 10 (LineageOS 14, Sec-Level 11/2018): it opens, reads the latest/missing messages off the XMPP-Server, displays them (marked "bold" in the userlist)... and a few seconds later (5-10 roughly) the application crashes. Cleaning the memory cache did not help (did not reset the application completely yet). Gajim connecting to the same XMPP account is working fine.

Logcat example as follows, first the start-up, and the crash around 7 seconds later.

Any help is welcome,

Kind regards, mistersixt

```01-16 17:49:48.011 D/conversations(20262): action: null
01-16 17:49:48.031 D/conversations(20262): ConversationsOverviewFragment.onStart()
01-16 17:49:48.033 D/conversations(20262): ConversationsOverviewFragment.onResume()
01-16 17:49:48.088 D/conversations(20262): ForegroundService: off
01-16 17:49:48.090 V/NativeCrypto(20262): Registering org/conscrypt/NativeCrypto's 287 native methods...
01-16 17:49:48.105 I/MemorizingTrustManager(20262): getAppKeyStore(/data/user/0/eu.siacs.conversations/app_KeyStore/KeyStore.bks) - file does not exist
01-16 17:49:48.105 D/NetworkSecurityConfig(20262): Using Network Security Config from resource network_security_configuration debugBuild: false
01-16 17:49:48.107 D/conversations(20262): initializing database...
01-16 17:49:48.107 D/conversations(20262): restoring accounts...
01-16 17:49:48.119 D/conversations(20262): restoring conversations...
01-16 17:49:48.126 D/conversations(20262): finished restoring conversations in 7ms
01-16 17:49:48.127 D/conversations(20262): restoring roster...
01-16 17:49:48.130 D/conversations(20262): starting file observer
01-16 17:49:48.139 D/conversations(20262): ForegroundService: on
01-16 17:49:48.139 D/conversations(20262): update unread count to 0
01-16 17:49:48.170 D/conversations(20262): ForegroundService: on
01-16 17:49:48.184 D/conversations(20262): restoring messages...
01-16 17:49:48.190 D/conversations(20262): <email omitted>: socket was null during force close
01-16 17:49:48.191 D/conversations(20262): <email omitted>: connecting
01-16 17:49:48.206 I/art     (20262): Do partial code cache collection, code=28KB, data=29KB
01-16 17:49:48.213 D/conversations(20262): EmojiService succeeded in loading fonts
01-16 17:49:48.220 I/art     (20262): After code cache collection, code=28KB, data=29KB
01-16 17:49:48.221 I/art     (20262): Increasing code cache capacity to 128KB
01-16 17:49:48.238 D/conversations(20262): start merging phone contacts with roster
01-16 17:49:48.241 D/conversations(20262): finished merging phone contacts
01-16 17:49:48.275 I/ActivityManager( 1268): Displayed eu.siacs.conversations/.ui.ConversationsActivity: +309ms (total +445ms)
01-16 17:49:48.278 D/conversations(20262): resetting all attempt counts
01-16 17:49:48.289 D/conversations(20262): app switched into foreground
01-16 17:49:48.435 D/conversations(20262): Resolver: [Result{ip='94.16.114.254', hostame='jabber-germany.de', port=5223, directTls=true, authenticated=false, priority=10}, Result{ip='2a03:4000:28:365::1', hostame='jabber-germany.de', port=5223, directTls=true, authenticated=false, priority=10}, Result{ip='94.16.114.254', hostame='jabber-germany.de', port=443, directTls=false, authenticated=false, priority=15}, Result{ip='2a03:4000:28:365::1', hostame='jabber-germany.de', port=443, directTls=false, authenticated=false, priority=15}, Result{ip='94.16.114.254', hostame='jabber-germany.de', port=443, directTls=true, authenticated=false, priority=20}, Result{ip='2a03:4000:28:365::1', hostame='jabber-germany.de', port=443, directTls=true, authenticated=false, priority=20}]
01-16 17:49:48.447 D/conversations(20262): updated dynamic shortcuts
01-16 17:49:48.506 D/conversations(20262): verified hostname null
01-16 17:49:48.506 D/conversations(20262): <email omitted>: using values from resolver jabber-germany.de/94.16.114.254:5223 tls: true
01-16 17:49:48.590 D/XmppDomainVerifier(20262): searching for jabber-germany.de in srvNames: [] xmppAddrs: [] domains:[conference.jabber-germany.de, jabber-germany.de, mail.jabber-germany.de, upload.jabber-germany.de, www.jabber-germany.de]
01-16 17:49:48.590 D/XmppDomainVerifier(20262): domain jabber-germany.de matched jabber-germany.de
01-16 17:49:48.656 D/conversations(20262): <email omitted>: protocol=TLSv1.2 cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
01-16 17:49:48.657 D/conversations(20262): <email omitted>/Conversations.Ya1S: Authenticating with SCRAM-SHA-1
01-16 17:49:48.701 I/art     (20262): Do partial code cache collection, code=56KB, data=61KB
01-16 17:49:48.701 I/art     (20262): After code cache collection, code=56KB, data=61KB
01-16 17:49:48.702 I/art     (20262): Increasing code cache capacity to 256KB
01-16 17:49:48.752 D/conversations(20262): <email omitted>: logged in
01-16 17:49:48.797 D/conversations(20262): finished restoring messages in 610ms
01-16 17:49:48.837 D/conversations(20262): <email omitted>: not counting stanza(IqPacket). Not in smacks session.
01-16 17:49:48.838 D/conversations(20262): <email omitted>: starting service discovery
01-16 17:49:48.844 D/conversations(20262): <email omitted>: server caps came from cache
01-16 17:49:48.851 D/conversations(20262): <email omitted>: stream management(3) enabled (resumable)
01-16 17:49:48.876 D/conversations(20262): <email omitted>: Requesting block list
01-16 17:49:48.896 D/conversations(20262): <email omitted>: successfully enabled carbons
01-16 17:49:48.897 D/conversations(20262): Received blocklist update from server
01-16 17:49:48.972 D/conversations(20262): AxolotlService (<email omitted>): Bundle 287351109 in PEP was current
01-16 17:49:48.972 D/conversations(20262): AxolotlService (<email omitted>): Announcing device 287351109
01-16 17:49:48.976 D/conversations(20262): <email omitted>: online with resource Conversations.Ya1S
01-16 17:49:48.977 D/conversations(20262): <email omitted>: fetching roster version 49
01-16 17:49:48.985 D/conversations(20262): <email omitted>: has push support
01-16 17:49:48.985 D/conversations(20262): <email omitted>: running mam query with=*, order=NORMAL, after=2019-01-16-4e7fa2401175ed00, catchup=true, ns=urn:xmpp:mam:2
01-16 17:49:48.986 D/conversations(20262): <email omitted> sending csi//active
01-16 17:49:48.992 D/conversations(20262): <email omitted>: retrieved own device list: [33707768, 965433479, 287351109]
01-16 17:49:49.011 D/conversations(20262): AxolotlService (<email omitted>): Received PEP device list [33707768, 965433479, 287351109] update from <email omitted>, processing... 
01-16 17:49:49.011 D/conversations(20262): <email omitted>: ignoring duplicate own device id list
01-16 17:49:49.012 D/conversations(20262): <email omitted>: ignoring bookmark PEP event because bookmark conversion was not detected
01-16 17:49:49.013 D/conversations(20262): AxolotlService (<email omitted>): Received PEP device list [1818337576] update from tablet-<email omitted>, processing... 
01-16 17:49:49.016 D/conversations(20262): AxolotlService (<email omitted>): Received PEP device list [508095145] update from <email omitted>, processing... 
01-16 17:49:49.021 D/conversations(20262): AxolotlService (<email omitted>): Received PEP device list [1740766337] update from <email omitted>, processing... 
01-16 17:49:49.024 D/conversations(20262): AxolotlService (<email omitted>): Received PEP device list [2093710637, 197235269] update from <email omitted>, processing... 
01-16 17:49:49.030 D/conversations(20262): AxolotlService (<email omitted>): Received PEP device list [751546156] update from <email omitted>, processing... 
01-16 17:49:49.057 D/conversations(20262): <email omitted>: finished mam after 1(0) messages. messages left=true count=null
01-16 17:49:49.057 D/conversations(20262): <email omitted>: found 0 pending receipt requests
01-16 17:49:49.058 D/conversations(20262): skipping shortcut update
01-16 17:49:49.059 D/conversations(20262): <email omitted>: joining conversation <email omitted>/topmodel
01-16 17:49:49.060 D/conversations(20262): <email omitted>: running mam query to=<email omitted>, start=2019-01-15T07:39:04.179Z, order=NORMAL, catchup=true, ns=urn:xmpp:mam:2
01-16 17:49:49.061 D/conversations(20262): <email omitted>: fetching members for Eichendorffstrasse-8
01-16 17:49:49.077 D/conversations(20262): <email omitted>: persisted roster in 23ms
01-16 17:49:49.380 D/conversations(20262): <email omitted>: finished mam after 0(0) messages. messages left=true count=0
01-16 17:49:49.380 D/conversations(20262): <email omitted>: found 0 pending receipt requests
01-16 17:49:49.382 D/conversations(20262): <email omitted>: successfully enabled push on server
...
...
...
01-16 17:49:57.274 E/AndroidRuntime(20262): FATAL EXCEPTION: pool-1-thread-1
01-16 17:49:57.274 E/AndroidRuntime(20262): Process: eu.siacs.conversations, PID: 20262
01-16 17:49:57.274 E/AndroidRuntime(20262): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
01-16 17:49:57.274 E/AndroidRuntime(20262):     at eu.siacs.conversations.persistance.FileBackend.getFileForPath(FileBackend.java:482)
01-16 17:49:57.274 E/AndroidRuntime(20262):     at eu.siacs.conversations.persistance.FileBackend.getFileForPath(FileBackend.java:477)
01-16 17:49:57.274 E/AndroidRuntime(20262):     at eu.siacs.conversations.services.XmppConnectionService.checkForDeletedFiles(XmppConnectionService.java:1072)
01-16 17:49:57.274 E/AndroidRuntime(20262):     at eu.siacs.conversations.services.XmppConnectionService.lambda$o-uIuPrJzYqCh3TTkc9haNUmZGU(XmppConnectionService.java)
01-16 17:49:57.274 E/AndroidRuntime(20262):     at eu.siacs.conversations.services.-$$Lambda$XmppConnectionService$o-uIuPrJzYqCh3TTkc9haNUmZGU.run(lambda)
01-16 17:49:57.274 E/AndroidRuntime(20262):     at eu.siacs.conversations.utils.SerialSingleThreadExecutor$Runner.run(SerialSingleThreadExecutor.java:58)
01-16 17:49:57.274 E/AndroidRuntime(20262):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
01-16 17:49:57.274 E/AndroidRuntime(20262):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
01-16 17:49:57.274 E/AndroidRuntime(20262):     at java.lang.Thread.run(Thread.java:761)
01-16 17:49:57.279 W/ActivityManager( 1268):   Force finishing activity eu.siacs.conversations/.ui.ConversationsActivity
01-16 17:49:57.310 D/conversations(20262): ConversationsOverviewFragment.onPause()
01-16 17:49:57.378 I/OpenGLRenderer( 1268): Initialized EGL, version 1.4
01-16 17:49:57.378 D/OpenGLRenderer( 1268): Swap behavior 1
01-16 17:49:57.738 D/conversations(20262): app switched into background
01-16 17:49:58.638 I/ActivityManager( 1268): Killing 20262:eu.siacs.conversations/u0a82 (adj 200): crash
01-16 17:49:58.638 D/ActivityManager( 1268): cleanUpApplicationRecord -- 20262
01-16 17:49:59.047 D/conversations(20320): ForegroundService: off
```

**Comment by iNPUTmice** [comment]
I’ve uploaded an APK with that fix http://gultsch.de/files/Conversations-2.3.11-conversations-playstore-compat-release.apk which should install right over the play store version.

**Comment by mistersixt** [comment]
Thanks a lot for the speedy fix, working like a charme ;-) !

**Comment by arendtio** [comment]
Does someone know when f-droid will distribute version 2.3.12? Version 2.3.11+fcr crashes for me too, but since the issue seems to be fixed I am just waiting for the new version to arrive. However, according to Github version 2.3.12 was tagged two days ago, yet [f-droid](https://f-droid.org/de/packages/eu.siacs.conversations/) still distributes the broken 2.3.11+fcr.
