### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by jkufner** [siacs/Conversations#3351]
#### General information

* **Version:** 2.3.11+fcr (I've just upgraded from the previous version)
* **Device:** Samsung S4 mini
* **Android Version:** 4.4.4
* **Server name:** self hosted (no recent configuration changes)
* **Server software:** ejabberd 18.9 from Debian
* **Installed server modules:** last time I checked Conversations reported all XEPs supported
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Launch Conversations

#### Expected result

Conversations started as usual.

#### Actual result

Crash.

#### Debug output

Background service seems to be running just fine, the crash occurs just after the main activity is displayed.

````
E/AndroidRuntime( 6351): FATAL EXCEPTION: pool-1-thread-1
E/AndroidRuntime( 6351): Process: eu.siacs.conversations, PID: 6351
E/AndroidRuntime( 6351): java.lang.NullPointerException
E/AndroidRuntime( 6351):        at eu.siacs.conversations.persistance.FileBackend.getFileForPath(FileBackend.java:482)
E/AndroidRuntime( 6351):        at eu.siacs.conversations.persistance.FileBackend.getFileForPath(FileBackend.java:477)
E/AndroidRuntime( 6351):        at eu.siacs.conversations.services.XmppConnectionService.checkForDeletedFiles(XmppConnectionService.java:1072)
E/AndroidRuntime( 6351):        at eu.siacs.conversations.services.XmppConnectionService.lambda$o-uIuPrJzYqCh3TTkc9haNUmZGU(XmppConnectionService.java)
E/AndroidRuntime( 6351):        at eu.siacs.conversations.services.-$$Lambda$XmppConnectionService$o-uIuPrJzYqCh3TTkc9haNUmZGU.run(lambda)
E/AndroidRuntime( 6351):        at eu.siacs.conversations.utils.SerialSingleThreadExecutor$Runner.run(SerialSingleThreadExecutor.java:58)
E/AndroidRuntime( 6351):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime( 6351):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime( 6351):        at java.lang.Thread.run(Thread.java:841)
W/ActivityManager(  789):   Force finishing activity eu.siacs.conversations/.ui.ConversationsActivity
````

**Comment by iNPUTmice** [comment]
See #3350

**Comment by jkufner** [comment]
Unfortunately, Android 4.4.4 does not have the option to allow/deny permissions yet.
