### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith

### ISSUE THREAD

**Issue by allo-** [siacs/Conversations#3363]
#### General information

* **Version:** 2.3.11+fcr
* **Device:** Google Nexus 5x
* **Android Version:** 6.0 Lineage OS
* **Conversations source:** F-Droid

After the upgrade to 2.3.11 conversations crashes every few seconds.
Stacktraces below

#### Debug output

````
adb logcat -s conversations

01-28 19:45:28.676 14723 14752 E AndroidRuntime: FATAL EXCEPTION: pool-1-thread-1
01-28 19:45:28.676 14723 14752 E AndroidRuntime: Process: eu.siacs.conversations, PID: 14723
01-28 19:45:28.676 14723 14752 E AndroidRuntime: Theme: themes:{}
01-28 19:45:28.676 14723 14752 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
01-28 19:45:28.676 14723 14752 E AndroidRuntime: 	at eu.siacs.conversations.persistance.FileBackend.getFileForPath(FileBackend.java:482)
01-28 19:45:28.676 14723 14752 E AndroidRuntime: 	at eu.siacs.conversations.persistance.FileBackend.getFileForPath(FileBackend.java:477)
01-28 19:45:28.676 14723 14752 E AndroidRuntime: 	at eu.siacs.conversations.services.XmppConnectionService.checkForDeletedFiles(XmppConnectionService.java:1072)
01-28 19:45:28.676 14723 14752 E AndroidRuntime: 	at eu.siacs.conversations.services.XmppConnectionService.lambda$o-uIuPrJzYqCh3TTkc9haNUmZGU(XmppConnectionService.java)
01-28 19:45:28.676 14723 14752 E AndroidRuntime: 	at eu.siacs.conversations.services.-$$Lambda$XmppConnectionService$o-uIuPrJzYqCh3TTkc9haNUmZGU.run(lambda)
01-28 19:45:28.676 14723 14752 E AndroidRuntime: 	at eu.siacs.conversations.utils.SerialSingleThreadExecutor$Runner.run(SerialSingleThreadExecutor.java:58)
01-28 19:45:28.676 14723 14752 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
01-28 19:45:28.676 14723 14752 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
01-28 19:45:28.676 14723 14752 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
01-28 19:45:28.755  5315  6761 W ActivityManager:   Force finishing activity eu.siacs.conversations/.ui.ConversationsActivity


````

The File access could possibly be through the android storage api (from providers like dropbox, etc.) from Seafile. I had e.g. in the log

````
01-28 19:49:47.379 11797 12002 V SeafileObserver: FileAlterationObserver[file='/storage/emulated/0/Seafile/REDACTED', listeners=1] finished checking event!
01-28 19:49:47.381 11797 12002 V SeafileObserver: FileAlterationObserver[file='/storage/emulated/0/Seafile/REDACTED', listeners=1] start checking event!
01-28 19:49:47.422 11797 12002 V SeafileObserver: FileAlterationObserver[file='/storage/emulated/0/Seafile/REDACTED', listeners=1] finished checking event!
````

before a crash.

**Comment by allo-** [comment]
I just saw the new version in F-Droid and installed it and wanted to report back in a few minutes, when I am sure it is working now.
Thank you.
