### ISSUE TITLE
Conversations crash during startup after installing 2.5.12

### ISSUE THREAD

**Issue by Etua** [siacs/Conversations#3566]
#### General information

* **Version:** 2.5.12+fcr
* **Device:** Samsung Galaxy S5
* **Android Version:**  Android 9 (LineageOS)
* **Server name:** self hosted
* **Server software:** prosody 0.11.2-1
* **Installed server modules:** 100% compliance
* **Conversations source:** F-Droid

#### Steps to reproduce

Try to open the app. This issue first appeared in the last few days so it may have been triggered by an update but I am not entirely sure about that.

#### Expected result

Conversations are opened and can be used without any problem.

#### Actual result
Conversations cannot be opened. No UI is visible. Android dialogue informing that the app has crashed is presented.

#### Debug output

````
adb -d logcat -v time -s conversations
--------- beginning of system
--------- beginning of crash
--------- beginning of main
10-18 00:02:14.523 D/conversations(20551): action: null
10-18 00:02:14.556 D/conversations(20551): ConversationsOverviewFragment.onStart()
10-18 00:02:14.557 D/conversations(20551): ConversationsOverviewFragment.onResume()
10-18 00:02:14.643 D/conversations(20551): ForegroundService: off
10-18 00:02:14.772 D/conversations(20551): initializing database...
10-18 00:02:14.773 D/conversations(20551): restoring accounts...
10-18 00:02:14.787 D/conversations(20551): restoring conversations...
10-18 00:02:14.793 D/conversations(20551): finished restoring conversations in 6ms
10-18 00:02:14.793 D/conversations(20551): restoring roster...
10-18 00:02:14.794 D/conversations(20551): starting file observer
10-18 00:02:14.798 D/conversations(20551): ForegroundService: off
10-18 00:02:14.798 D/conversations(20551): update unread count to 0
10-18 00:02:14.805 D/conversations(20551): ForegroundService: off
10-18 00:02:14.810 D/conversations(20551): dominik@danelski.pl: connecting
10-18 00:02:14.820 D/conversations(20551): restoring messages...
10-18 00:02:15.000 D/conversations(20551): resetting all attempt counts
10-18 00:02:16.317 D/conversations(20632): ForegroundService: off
10-18 00:02:16.538 D/conversations(20632): initializing database...
10-18 00:02:16.539 D/conversations(20632): restoring accounts...
10-18 00:02:16.560 D/conversations(20632): restoring conversations...
10-18 00:02:16.568 D/conversations(20632): finished restoring conversations in 8ms
10-18 00:02:16.571 D/conversations(20632): restoring roster...
10-18 00:02:16.576 D/conversations(20632): starting file observer
10-18 00:02:16.583 D/conversations(20632): ForegroundService: off
10-18 00:02:16.583 D/conversations(20632): update unread count to 0
10-18 00:02:16.594 D/conversations(20632): ForegroundService: off
10-18 00:02:16.605 D/conversations(20632): dominik@danelski.pl: connecting
10-18 00:02:16.608 D/conversations(20632): resetting all attempt counts
10-18 00:02:16.612 D/conversations(20632): restoring messages...
10-18 00:02:16.628 D/conversations(20632): start merging phone contacts with roster
10-18 00:02:16.628 D/conversations(20632): finished merging phone contacts
10-18 00:02:16.796 D/conversations(20632): Resolver: [Result{ip='185.20.172.155', hostame='danelski.pl', port=5222, directTls=false, authenticated=false, priority=5}]
10-18 00:02:16.798 D/conversations(20632): verified hostname null
10-18 00:02:16.798 D/conversations(20632): dominik@danelski.pl: using values from resolver danelski.pl/185.20.172.155:5222 tls: false
10-18 00:02:16.854 D/conversations(20632): updated dynamic shortcuts
10-18 00:02:17.224 D/conversations(20632): dominik@danelski.pl: TLS connection established
10-18 00:02:17.399 D/conversations(20632): dominik@danelski.pl: protocol=TLSv1.3 cipher=TLS_AES_256_GCM_SHA384
10-18 00:02:17.412 D/conversations(20632): dominik@danelski.pl/Conversations.7za7: Authenticating with SCRAM-SHA-1
10-18 00:02:17.587 D/conversations(20632): found 0 changed files on start up. total=90. (125ms)
10-18 00:02:17.665 D/conversations(20632): dominik@danelski.pl: logged in
10-18 00:03:47.909 D/conversations(20986): ForegroundService: off
10-18 00:03:48.033 D/conversations(20986): initializing database...
10-18 00:03:48.034 D/conversations(20986): restoring accounts...
10-18 00:03:48.050 D/conversations(20986): restoring conversations...
10-18 00:03:48.055 D/conversations(20986): finished restoring conversations in 4ms
10-18 00:03:48.056 D/conversations(20986): restoring roster...
10-18 00:03:48.057 D/conversations(20986): starting file observer
10-18 00:03:48.061 D/conversations(20986): ForegroundService: off
10-18 00:03:48.061 D/conversations(20986): update unread count to 0
10-18 00:03:48.073 D/conversations(20986): ForegroundService: off
10-18 00:03:48.080 D/conversations(20986): restoring messages...
10-18 00:03:48.102 D/conversations(20986): resetting all attempt counts
10-18 00:03:48.105 D/conversations(20986): dominik@danelski.pl: connecting
10-18 00:03:48.134 D/conversations(20986): start merging phone contacts with roster
10-18 00:03:48.135 D/conversations(20986): finished merging phone contacts
````

I also performed adb logcat without specifying "-s conversations" and that's what I found: 
````
10-18 00:16:32.164 21529 21548 W CursorWindow: Window is full: requested allocation 2097451 bytes, free space 2096270 bytes, window size 2097152 bytes
10-18 00:16:32.165 21529 21548 E SQLiteQuery: exception: Row too big to fit into CursorWindow requiredPos=1, totalRows=2; query: SELECT * FROM messages WHERE conversationUuid=? ORDER BY timeSent DESC LIMIT 50
10-18 00:16:32.167 21529 21548 E AndroidRuntime: FATAL EXCEPTION: pool-4-thread-1
10-18 00:16:32.167 21529 21548 E AndroidRuntime: Process: eu.siacs.conversations, PID: 21529
10-18 00:16:32.167 21529 21548 E AndroidRuntime: android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=1, totalRows=2
10-18 00:16:32.167 21529 21548 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
10-18 00:16:32.167 21529 21548 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:895)
10-18 00:16:32.167 21529 21548 E AndroidRuntime: 	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
10-18 00:16:32.167 21529 21548 E AndroidRuntime: 	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
10-18 00:16:32.167 21529 21548 E AndroidRuntime: 	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:157)
10-18 00:16:32.167 21529 21548 E AndroidRuntime: 	at android.database.sqlite.SQLiteCursor.onMove(SQLiteCursor.java:128)
10-18 00:16:32.167 21529 21548 E AndroidRuntime: 	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:237)
10-18 00:16:32.167 21529 21548 E AndroidRuntime: 	at android.database.AbstractCursor.moveToNext(AbstractCursor.java:269)
10-18 00:16:32.167 21529 21548 E AndroidRuntime: 	at eu.siacs.conversations.persistance.DatabaseBackend.getMessages(DatabaseBackend.java:757)
10-18 00:16:32.167 21529 21548 E AndroidRuntime: 	at eu.siacs.conversations.persistance.DatabaseBackend.getMessages(DatabaseBackend.java:737)
10-18 00:16:32.167 21529 21548 E AndroidRuntime: 	at eu.siacs.conversations.services.XmppConnectionService.restoreMessages(XmppConnectionService.java:1791)
10-18 00:16:32.167 21529 21548 E AndroidRuntime: 	at eu.siacs.conversations.services.XmppConnectionService.lambda$restoreFromDatabase$15$XmppConnectionService(XmppConnectionService.java:1777)
10-18 00:16:32.167 21529 21548 E AndroidRuntime: 	at eu.siacs.conversations.services.-$$Lambda$XmppConnectionService$ZDhFBbVozOlFu66RgzOX7pHvp6o.run(Unknown Source:2)
10-18 00:16:32.167 21529 21548 E AndroidRuntime: 	at eu.siacs.conversations.utils.SerialSingleThreadExecutor$Runner.run(SerialSingleThreadExecutor.java:58)
10-18 00:16:32.167 21529 21548 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-18 00:16:32.167 21529 21548 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-18 00:16:32.167 21529 21548 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
10-18 00:16:32.172   546   622 I ActivityManager: Showing crash dialog for package eu.siacs.conversations u0
````

**Comment by dsdeeptisharma** [comment]
Hi, I have a question. Does this app compress the image before sending to other person?

**Comment by licaon-kter** [comment]
@dsdeeptisharma See its Settings, in can do that if you wish.

**Comment by licaon-kter** [comment]
Android does not allow downgrade


Maybe this https://nitter.net/iNPUTmice/status/1181180205425147906#m ?

**Comment by Etua** [comment]
@licaon-kter I suppose that you wrote that to @Anmibe?

**Comment by immanuelfodor** [comment]
Same here after Play Store update to 2.6.0-pcr. App crashes immediately after open. Oneplus 7 with Oxygen OS 10.0.1

**Comment by immanuelfodor** [comment]
Clearing the cache doesn't help and erasing app data is not an option because of personal OMEMO trusts, please push a fix/revert to Play Store

**Comment by iNPUTmice** [comment]
@immanuelfodor with the same stack trace?

**Comment by immanuelfodor** [comment]
I didn't run it before, now here it is, I opened the app 4 times, redacted values are between <>:

```
adb -d logcat -v time -s conversations                                                                                                                                                                                        
--------- beginning of crash
--------- beginning of system
--------- beginning of main
11-11 18:49:28.980 D/conversations(12554): ForegroundService: on
11-11 18:49:29.017 D/conversations(12554): initializing database...
11-11 18:49:29.018 D/conversations(12554): restoring accounts...
11-11 18:49:29.027 D/conversations(12554): restoring conversations...
11-11 18:49:29.030 D/conversations(12554): finished restoring conversations in 4ms
11-11 18:49:29.031 D/conversations(12554): restoring roster...
11-11 18:49:29.033 D/conversations(12554): starting file observer
11-11 18:49:29.037 D/conversations(12554): ForegroundService: on
11-11 18:49:29.037 D/conversations(12554): update unread count to 0
11-11 18:49:29.044 D/conversations(12554): ForegroundService: on
11-11 18:49:29.045 D/conversations(12554): ignoring onTaskRemoved because foreground service is activated
11-11 18:49:29.056 D/conversations(12554): resetting all attempt counts
11-11 18:49:29.062 D/conversations(12554): <myusername>@<fqdn>: connecting
11-11 18:49:29.067 D/conversations(12554): restoring messages...
11-11 18:49:29.083 D/conversations(12554): action: null
11-11 18:49:29.098 D/conversations(12554): start merging phone contacts with roster
11-11 18:49:29.098 D/conversations(12554): finished merging phone contacts
11-11 18:49:29.105 D/conversations(12554): ConversationsOverviewFragment.onStart()
11-11 18:49:29.106 D/conversations(12554): ConversationsOverviewFragment.onResume()
11-11 18:49:29.183 D/conversations(12554): EmojiService succeeded in loading fonts
11-11 18:49:29.184 D/conversations(12554): app switched into foreground
11-11 18:49:29.293 D/conversations(12554): updated dynamic shortcuts
11-11 18:49:29.299 D/conversations(12554): ConversationsOverviewFragment.onPause()

11-11 18:49:40.853 D/conversations(12709): ForegroundService: on
11-11 18:49:40.877 D/conversations(12709): initializing database...
11-11 18:49:40.877 D/conversations(12709): restoring accounts...
11-11 18:49:40.883 D/conversations(12709): restoring conversations...
11-11 18:49:40.886 D/conversations(12709): finished restoring conversations in 3ms
11-11 18:49:40.886 D/conversations(12709): restoring roster...
11-11 18:49:40.887 D/conversations(12709): starting file observer
11-11 18:49:40.890 D/conversations(12709): ForegroundService: on
11-11 18:49:40.890 D/conversations(12709): update unread count to 0
11-11 18:49:40.899 D/conversations(12709): ForegroundService: on
11-11 18:49:40.910 D/conversations(12709): <myusername>@<fqdn>: connecting
11-11 18:49:40.916 D/conversations(12709): restoring messages...
11-11 18:49:40.927 D/conversations(12709): resetting all attempt counts
11-11 18:49:40.945 D/conversations(12709): start merging phone contacts with roster
11-11 18:49:40.945 D/conversations(12709): finished merging phone contacts
11-11 18:49:40.957 D/conversations(12709): action: null
11-11 18:49:40.971 D/conversations(12709): updated dynamic shortcuts
11-11 18:49:41.010 D/conversations(12709): ConversationsOverviewFragment.onStart()
11-11 18:49:41.013 D/conversations(12709): ConversationsOverviewFragment.onResume()
11-11 18:49:41.130 D/conversations(12709): ConversationsOverviewFragment.onPause()
11-11 18:49:41.135 D/conversations(12709): EmojiService succeeded in loading fonts
11-11 18:49:41.138 D/conversations(12709): app switched into foreground
11-11 18:49:41.211 D/conversations(12709): app switched into background
11-11 18:49:41.342 D/conversations(12709): found 0 changed files on start up. total=140. (57ms)

11-11 18:49:53.342 D/conversations(12870): action: null
11-11 18:49:53.355 D/conversations(12870): ConversationsOverviewFragment.onStart()
11-11 18:49:53.356 D/conversations(12870): ConversationsOverviewFragment.onResume()
11-11 18:49:53.415 D/conversations(12870): ForegroundService: on
11-11 18:49:53.439 D/conversations(12870): initializing database...
11-11 18:49:53.439 D/conversations(12870): restoring accounts...
11-11 18:49:53.444 D/conversations(12870): restoring conversations...
11-11 18:49:53.447 D/conversations(12870): finished restoring conversations in 3ms
11-11 18:49:53.448 D/conversations(12870): restoring roster...
11-11 18:49:53.449 D/conversations(12870): starting file observer
11-11 18:49:53.452 D/conversations(12870): ForegroundService: on
11-11 18:49:53.452 D/conversations(12870): update unread count to 0
11-11 18:49:53.463 D/conversations(12870): ForegroundService: on
11-11 18:49:53.467 D/conversations(12870): <myusername>@<fqdn>: connecting
11-11 18:49:53.469 D/conversations(12870): EmojiService succeeded in loading fonts
11-11 18:49:53.469 D/conversations(12870): restoring messages...
11-11 18:49:53.486 D/conversations(12870): resetting all attempt counts
11-11 18:49:53.491 D/conversations(12870): app switched into foreground
11-11 18:49:53.495 D/conversations(12870): start merging phone contacts with roster
11-11 18:49:53.496 D/conversations(12870): finished merging phone contacts
11-11 18:49:53.544 D/conversations(12870): updated dynamic shortcuts
11-11 18:49:53.596 D/conversations(12870): ConversationsOverviewFragment.onPause()
11-11 18:49:53.617 D/conversations(12870): Resolver: [Result{ip='<ip>', hostame='<fqdn>', port=5223, directTls=true, authenticated=false, priority=0}, Result{ip='<ip>', hostame='<fqdn>', port=5222, directTls=false, authenticated=false, priority=0}]
11-11 18:49:53.632 D/conversations(12870): verified hostname null
11-11 18:49:53.632 D/conversations(12870): <myusername>@<fqdn>: using values from resolver <fqdn>/<ip>:5223 tls: true
11-11 18:49:53.672 D/conversations(12870): app switched into background
11-11 18:49:53.777 D/conversations(12870): <myusername>@<fqdn>: protocol=TLSv1.3 cipher=TLS_AES_256_GCM_SHA384
11-11 18:49:53.778 D/conversations(12870): <myusername>@<fqdn>/Conversations.a2Fe: Authenticating with SCRAM-SHA-1
11-11 18:49:53.784 D/conversations(12870): found 0 changed files on start up. total=140. (227ms)
11-11 18:49:53.809 D/conversations(12870): <myusername>@<fqdn>: logged in

11-11 18:49:58.800 D/conversations(12954): action: null
11-11 18:49:58.813 D/conversations(12954): ConversationsOverviewFragment.onStart()
11-11 18:49:58.813 D/conversations(12954): ConversationsOverviewFragment.onResume()
11-11 18:49:58.875 D/conversations(12954): ForegroundService: on
11-11 18:49:58.899 D/conversations(12954): initializing database...
11-11 18:49:58.899 D/conversations(12954): restoring accounts...
11-11 18:49:58.904 D/conversations(12954): restoring conversations...
11-11 18:49:58.906 D/conversations(12954): finished restoring conversations in 2ms
11-11 18:49:58.907 D/conversations(12954): restoring roster...
11-11 18:49:58.908 D/conversations(12954): starting file observer
11-11 18:49:58.910 D/conversations(12954): ForegroundService: on
11-11 18:49:58.910 D/conversations(12954): update unread count to 0
11-11 18:49:58.916 D/conversations(12954): ForegroundService: on
11-11 18:49:58.920 D/conversations(12954): <myusername>@<fqdn>: connecting
11-11 18:49:58.931 D/conversations(12954): EmojiService succeeded in loading fonts
11-11 18:49:58.948 D/conversations(12954): app switched into foreground
11-11 18:49:58.950 D/conversations(12954): resetting all attempt counts
11-11 18:49:58.955 D/conversations(12954): restoring messages...
11-11 18:49:58.971 D/conversations(12954): start merging phone contacts with roster
11-11 18:49:58.971 D/conversations(12954): finished merging phone contacts
11-11 18:49:58.992 D/conversations(12954): Resolver: [Result{ip='<ip>', hostame='<fqdn>', port=5223, directTls=true, authenticated=false, priority=0}, Result{ip='<ip>', hostame='<fqdn>', port=5222, directTls=false, authenticated=false, priority=0}]
11-11 18:49:58.997 D/conversations(12954): updated dynamic shortcuts
11-11 18:49:59.045 D/conversations(12954): verified hostname null
11-11 18:49:59.045 D/conversations(12954): <myusername>@<fqdn>: using values from resolver <fqdn>/<ip>:5223 tls: true
11-11 18:49:59.062 D/conversations(12954): ConversationsOverviewFragment.onPause()
11-11 18:49:59.122 D/conversations(12954): <myusername>@<fqdn>: protocol=TLSv1.3 cipher=TLS_AES_256_GCM_SHA384
11-11 18:49:59.123 D/conversations(12954): <myusername>@<fqdn>/Conversations.a2Fe: Authenticating with SCRAM-SHA-1
11-11 18:49:59.124 D/conversations(12954): app switched into background
11-11 18:49:59.180 D/conversations(12954): <myusername>@<fqdn>: logged in
11-11 18:49:59.206 D/conversations(12954): found 0 changed files on start up. total=140. (124ms)
^C
```

Without the -s conversations part there is indeed the same SQL exception:

```
11-11 18:56:58.610 W/CursorWindow(13508): Window is full: requested allocation 6088026 bytes, free space 2093393 bytes, window size 2097152 bytes
11-11 18:56:58.610 W/CursorWindow(13508): Window is full: requested allocation 6088026 bytes, free space 2096357 bytes, window size 2097152 bytes
11-11 18:56:58.612 E/ndroid.systemu( 2153): Invalid ID 0x00000000.
11-11 18:56:58.612 E/SQLiteQuery(13508): exception: Row too big to fit into CursorWindow requiredPos=14, totalRows=15; query: SELECT * FROM messages WHERE conversationUuid=? ORDER BY timeSent DESC LIMIT 50
11-11 18:56:58.617 E/ndroid.systemu( 2153): Invalid ID 0x00000000.
11-11 18:56:58.619 D/conversations(13508): updated dynamic shortcuts
11-11 18:56:58.619 E/ndroid.systemu( 2153): Invalid ID 0x00000000.
11-11 18:56:58.620 E/AndroidRuntime(13508): FATAL EXCEPTION: pool-4-thread-1
11-11 18:56:58.620 E/AndroidRuntime(13508): Process: eu.siacs.conversations, PID: 13508
11-11 18:56:58.620 E/AndroidRuntime(13508): android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=14, totalRows=15
11-11 18:56:58.620 E/AndroidRuntime(13508):     at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
11-11 18:56:58.620 E/AndroidRuntime(13508):     at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:942)
11-11 18:56:58.620 E/AndroidRuntime(13508):     at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:838)
11-11 18:56:58.620 E/AndroidRuntime(13508):     at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
11-11 18:56:58.620 E/AndroidRuntime(13508):     at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:161)
11-11 18:56:58.620 E/AndroidRuntime(13508):     at android.database.sqlite.SQLiteCursor.onMove(SQLiteCursor.java:131)
11-11 18:56:58.620 E/AndroidRuntime(13508):     at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:249)
11-11 18:56:58.620 E/AndroidRuntime(13508):     at android.database.AbstractCursor.moveToNext(AbstractCursor.java:281)
11-11 18:56:58.620 E/AndroidRuntime(13508):     at eu.siacs.conversations.persistance.DatabaseBackend.getMessages(DatabaseBackend.java:757)
11-11 18:56:58.620 E/AndroidRuntime(13508):     at eu.siacs.conversations.persistance.DatabaseBackend.getMessages(DatabaseBackend.java:737)
11-11 18:56:58.620 E/AndroidRuntime(13508):     at eu.siacs.conversations.services.XmppConnectionService.restoreMessages(XmppConnectionService.java:1797)
11-11 18:56:58.620 E/AndroidRuntime(13508):     at eu.siacs.conversations.services.XmppConnectionService.lambda$restoreFromDatabase$15$XmppConnectionService(XmppConnectionService.java:1783)
11-11 18:56:58.620 E/AndroidRuntime(13508):     at eu.siacs.conversations.services.-$$Lambda$XmppConnectionService$ZDhFBbVozOlFu66RgzOX7pHvp6o.run(Unknown Source:2)
11-11 18:56:58.620 E/AndroidRuntime(13508):     at eu.siacs.conversations.utils.SerialSingleThreadExecutor$Runner.run(SerialSingleThreadExecutor.java:58)
11-11 18:56:58.620 E/AndroidRuntime(13508):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
11-11 18:56:58.620 E/AndroidRuntime(13508):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
11-11 18:56:58.620 E/AndroidRuntime(13508):     at java.lang.Thread.run(Thread.java:919)
11-11 18:56:58.620 E/ndroid.systemu( 2153): Invalid ID 0x00000000.
11-11 18:56:58.621 D/conversations(13508): verified hostname null
```

**Comment by immanuelfodor** [comment]
Updated a friend's phone as well, the same version (GPlay 2.6.0+pcr) on a Oneplus 5 + OxygenOS 9.0.9 works fine

**Comment by immanuelfodor** [comment]
I badly needed to contact somebody, so cleared app data besides cache, then logged in again (OP7), and it works fine just as before the update. Of course, I lost all my OMEMO trusts and encrypted message history but I was desperate :grinning:

**Comment by Anmibe** [comment]
I moved (temporarily?) to the fork "Conv6sations for Sum7" (2.5.12).

**Comment by licaon-kter** [comment]
@Anmibe And that doesn't crash on new install? But Conversations (on a new install) crashes?

**Comment by iNPUTmice** [comment]
Just for the record. This bug is not triggered by a particular version
(upgrade) of Conversations. It just manifests itself upon restart. And a
reinstall also triggers a restart. That's why down grading wouldn't fix
the issue. Cleaning the app data will help.

**Comment by hochwasser** [comment]
The error seems to be only on Android 9 present. With the android emulator and a backup from the device in the emulator restored it worked on Android 8. Android 9 does not work.
I tried the solution of [sqliteblobtoobigexception](https://stackoverflow.com/questions/51959944/ -row-too-big-to-fit-into-cursorwindow-requiredpos-0-t) and made a change to "DatabaseBackend.java:public ArrayList<Message> getMessages(Conversation conversation, int limit, long timestamp)"

This is the code. The CursorWindow and the AbstractWindowedCursor seem to be the solution.
I put it into its one if path:
```
if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.P) {
            CursorWindow cw = new CursorWindow("test", 5000000);
            AbstractWindowedCursor ac = (AbstractWindowedCursor) cursor;
            ac.setWindow(cw);
            try {
                while (ac.moveToNext()) {
                    try {
                        final Message message = Message.fromCursor(ac, conversation);
                        if (message != null) {
                            list.add(0, message);
                        }
                    } catch (Exception e) {
                        Log.e(Config.LOGTAG, "unable to restore message");
                    }
                }
            }catch (android.database.sqlite.SQLiteBlobTooBigException e){
                Log.e(Config.LOGTAG, "Exception", e);
            }
            ac.close();
        }
        else
        {
            Log.d(Config.LOGTAG, conversation.getAccountUuid());
            try {
                while (cursor.moveToNext()) {
                    try {
                        final Message message = Message.fromCursor(cursor, conversation);
                        if (message != null) {
                            list.add(0, message);
                        }
                    } catch (Exception e) {
                        Log.e(Config.LOGTAG, "unable to restore message");
                    }
                }
            }catch (android.database.sqlite.SQLiteBlobTooBigException e){
                Log.e(Config.LOGTAG, "Exception", e);
            }
            cursor.close();
        }
```

**Comment by iNPUTmice** [comment]
@hochwasser thank you for figuring that out. Please create a pull request so we can discuss this further. (From a first glance it looks like the code can be cleaned up (remove the duplicate code.))
