### ISSUE TITLE
Unable to upload files bigger then 5Mb(maybe less) with omemo enabled

### ISSUE THREAD

**Issue by massimilianoLe** [siacs/Conversations#3653]
#### General information

* **Version:** 2.7.0+fcr (364)
* **Device:** Fairphone, Samsung A50
* **Android Version:**  Android 9 (stock), lineageOs 16
* **Server name:** disroot.org, self hosted
* **Server software:** Prosody trunk nightly build 1238 (2020-02-28, 5efd6865486) and Metronome 3.12.0 
* **Installed server modules:** Stream Managment, CSI, MAM, http_upload
* **Conversations source:** F-Droid

#### Steps to reproduce

1. enable OMEMO
2. upload a file that is bigger then 5Mb maybe less

#### Expected result
file to get uploaded

#### Actual result

Upload stays on 0% and after wile error message:

Write error: ssl=0xa1f45168: I/O error
during system call, Broken pipe

#### Debug output

![Screenshot_20200306-222904_Conversations](https://user-images.githubusercontent.com/44651815/76138467-4a5cf180-6040-11ea-9eec-2d2e76245004.jpg)
![Screenshot_20200306-223655_Conversations](https://user-images.githubusercontent.com/44651815/76138469-4af58800-6040-11ea-9938-1549e24eab22.jpg)

**Comment by mdosch** [comment]
I have the same issue but I didn't get an error. Instead conversations crashed with oom. 

```
Version: 2.7.0+fcr
Last Update: 2020-03-01
SHA-1: 20:ab:18:ba:4d:49:1d:f1:b7:bf:50:51:be:1f:e2:6e:b7:56:27:73

java.lang.OutOfMemoryError: Failed to allocate a 13780512 byte allocation with 12056360 free bytes and 11MB until OOM, max allowed footprint 201326592, growth limit 201326592
	at javax.crypto.CipherInputStream.getMoreData(CipherInputStream.java:121)
	at javax.crypto.CipherInputStream.read(CipherInputStream.java:249)
	at javax.crypto.CipherInputStream.read(CipherInputStream.java:225)
	at eu.siacs.conversations.http.HttpUploadConnection.upload(HttpUploadConnection.java:192)
	at eu.siacs.conversations.http.HttpUploadConnection.access$300(HttpUploadConnection.java:30)
	at eu.siacs.conversations.http.HttpUploadConnection$1.lambda$success$0(HttpUploadConnection.java:138)
	at eu.siacs.conversations.http.-$$Lambda$HttpUploadConnection$1$xe9LFzy6COS1JMdivVN6RPSpYq4.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:764)
```

**Comment by licaon-kter** [comment]
Yup confirmed, depends on free memory, eg. I can send 17Mb but not 32Mb
