### ISSUE TITLE
Security, expire sert

### ISSUE THREAD

**Issue by xoyteam** [siacs/Conversations#793]
After the expiration of the server certificate, the program does not warn me.
It's OK?

**Comment by Boris-de** [comment]
> After the expiration of the server certificate, the program does not warn me.

After my certificate expired I got a warning ("Accept unknown certificate? Could not validate certificate: null"). So generally the check seems to work.
Only the reason "null" is a bit unclear, but it seems that this message is from bouncycastle-android:

    java.security.cert.CertificateException: com.android.org.bouncycastle.jce.exception.ExtCertPathValidatorException: Could not validate certificate: null
       at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:308)
       at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:192)
       at de.duenndns.ssl.MemorizingTrustManager.checkCertTrusted(MemorizingTrustManager.java:418)
       at de.duenndns.ssl.MemorizingTrustManager.checkServerTrusted(MemorizingTrustManager.java:441)
       at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:614)
       at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
       at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:406)
       at com.android.org.conscrypt.OpenSSLSocketImpl.getSession(OpenSSLSocketImpl.java:742)
       at eu.siacs.conversations.xmpp.XmppConnection.switchOverToTls(XmppConnection.java:532)
       at eu.siacs.conversations.xmpp.XmppConnection.processStream(XmppConnection.java:265)
       at eu.siacs.conversations.xmpp.XmppConnection.connect(XmppConnection.java:218)
       at eu.siacs.conversations.xmpp.XmppConnection.run(XmppConnection.java:252)
       at java.lang.Thread.run(Thread.java:841)
    Caused by: com.android.org.bouncycastle.jce.exception.ExtCertPathValidatorException: Could not validate certificate: null
       at com.android.org.bouncycastle.jce.provider.RFC3280CertPathUtilities.processCertA(RFC3280CertPathUtilities.java:1488)
       at com.android.org.bouncycastle.jce.provider.PKIXCertPathValidatorSpi.engineValidate(PKIXCertPathValidatorSpi.java:305)
       at java.security.cert.CertPathValidator.validate(CertPathValidator.java:190)
       at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:295)
       ... 12 more
    Caused by: java.security.cert.CertificateExpiredException
       at com.android.org.conscrypt.OpenSSLX509Certificate.checkValidity(OpenSSLX509Certificate.java:220)
       at com.android.org.bouncycastle.jce.provider.RFC3280CertPathUtilities.processCertA(RFC3280CertPathUtilities.java:1483)
       ... 15 more
