### ISSUE TITLE
Crash on TLS Connection

### ISSUE THREAD

**Issue by knoy** [siacs/Conversations#816]
I'm receiving crash reports for the following:
java.lang.NullPointerException
	at eu.siacs.conversations.xmpp.XmppConnection.switchOverToTls(XmppConnection.java:555)
	at eu.siacs.conversations.xmpp.XmppConnection.processStream(XmppConnection.java:263)
	at eu.siacs.conversations.xmpp.XmppConnection.connect(XmppConnection.java:219)
	at eu.siacs.conversations.xmpp.XmppConnection.run(XmppConnection.java:250)
	at java.lang.Thread.run(Thread.java:841)

Which corresponds to the lines:
554: if (socket == null) throw new IOException("socket was null");
555: SSLSocket sslSocket = (SSLSocket) factory.createSocket(socket, socket.getInetAddress().getHostAddress(), socket.getPort(), true);

So it seems to be either a problem resolving the IP to a host or getting the port number of the socket.
Not sure if this is related to https://github.com/siacs/Conversations/issues/811

**Comment by iNPUTmice** [comment]
fixed in 3c5d7d4f1b8af9568fdc7ba17f4c6d0a11167a4e
