### ISSUE TITLE
MessageAdapter crash

### ISSUE THREAD

**Issue by knoy** [siacs/Conversations#824]
Not sure exactly what's triggering this but I've seen it quite a few times

java.lang.NullPointerException
	at eu.siacs.conversations.ui.adapter.MessageAdapter.getView(MessageAdapter.java:457)
	at android.widget.AbsListView.obtainView(AbsListView.java:2240)
	at android.widget.ListView.makeAndAddView(ListView.java:1790)
	at android.widget.ListView.fillUp(ListView.java:725)
	at android.widget.ListView.layoutChildren(ListView.java:1611)
	at android.widget.AbsListView.onLayout(AbsListView.java:2091)
	at android.view.View.layout(View.java:14817)
	at android.view.ViewGroup.layout(ViewGroup.java:4631)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
	at android.view.View.layout(View.java:14817)
	at android.view.ViewGroup.layout(ViewGroup.java:4631)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
	at android.view.View.layout(View.java:14817)
	at android.view.ViewGroup.layout(ViewGroup.java:4631)
	at android.support.v4.widget.SlidingPaneLayout.onLayout(SlidingPaneLayout.java:686)
	at android.view.View.layout(View.java:14817)
	at android.view.ViewGroup.layout(ViewGroup.java:4631)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
	at android.view.View.layout(View.java:14817)
	at android.view.ViewGroup.layout(ViewGroup.java:4631)
	at com.android.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:374)
	at android.view.View.layout(View.java:14817)
	at android.view.ViewGroup.layout(ViewGroup.java:4631)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
	at android.view.View.layout(View.java:14817)
	at android.view.ViewGroup.layout(ViewGroup.java:4631)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1987)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1744)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1000)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5670)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
	at android.view.Choreographer.doCallbacks(Choreographer.java:574)
	at android.view.Choreographer.doFrame(Choreographer.java:544)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5017)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:126)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by iNPUTmice** [comment]
Not sure exactly what caused this either but there is a work around in HEAD.

(The original cause seems to be a platform bug in the view recycling of the ListView)
