### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by kobra34** [siacs/Conversations#991]
Hi.
 İ have any bug report. But my system not send your server.

Version: 1.0
Last Update: 02 Feb. 14:17
java.lang.NullPointerException
at eu.siacs.conversations.ui.ConversationFragment$10.onClick(ConversationFragment.java:324)
at android.view.View.performClick(View.java:4101)
at android.view.View$PerformClick.run(View.java:17082)
at android.os.Handler.handleCallback(Handler.java:615)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4940)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:798)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:565)
at dalvik.system.NativeStart.main(Native Method)

**Comment by iNPUTmice** [comment]
Was this a one time thing? Or are you able to reproduce this by doing something specific?
